- docs/live-examples/css-examples/box-shadow.html
- docs/live-examples/css-examples/css/box-shadow.css
- docs/pages/css/box-shadow.html
- live-examples/css-examples/box-shadow.html
- live-examples/css-examples/css/box-shadow.css
- site.json
@wbamberg @stephaniehobson This adds `box-shadow` live examples but, at the same time demonstrates what a CSS PR would look like.
For this one in particular, you can ignore the files in `docs` as this will be added to `.gitignore` once I have set-up travis to generate the pages on merges to master.
So, had Travis already been set-up, this pull request would consist of:
`live-examples/css-examples/box-shadow.html`
`live-examples/css-examples/css/box-shadow.css`
and the update to `site.json`
> Adds box-shadow CSS exmaples

- css/editable-css.css
Not sure if these were intentionally left of in the latest revision but, I do feel they still offer some additional benefit. @stephaniehobson
> Adds left hand border color statuses back to CSS examples

- js/editor-libs/console.js
Here's a simple attempt to format logged objects to indicate their type:
* wrap strings in quotes
* wrap arrays in square brackets
> Format logged objects to indicate their type

- js/editor-libs/console.js
This is a tentative pull request for the enhancement of the console log types.
Building on the work by @wbamberg this change should add support for arrays of arrays and arrays of strings. As this method takes advantage of recursion it *should* work to any level of 'nesting'.
Note: we still don't have support for `Int32Array` et al as `Array.isArray()` returns `false` in those cases. Not sure what the best way to test for these cases are, but would be nice to, especially for the `SharedBufferArray` examples.
PS I added a space after commas and made it single quotes around strings, which I think is inline with our preference and browser console output.
> console.log support for arrays of arrays and arrays of strings

- live-examples/js-examples/regexp-constructor.html
- live-examples/js-examples/regexp-getregexp-@@species.html
- live-examples/js-examples/regexp-lastindex.html
- live-examples/js-examples/regexp-prototype-@@match.html
- live-examples/js-examples/regexp-prototype-@@replace.html
- live-examples/js-examples/regexp-prototype-@@search.html
- live-examples/js-examples/regexp-prototype-@@split.html
- live-examples/js-examples/regexp-prototype-exec.html
- live-examples/js-examples/regexp-prototype-flags.html
- live-examples/js-examples/regexp-prototype-global.html
- live-examples/js-examples/regexp-prototype-ignorecase.html
- live-examples/js-examples/regexp-prototype-multiline.html
- live-examples/js-examples/regexp-prototype-source.html
- live-examples/js-examples/regexp-prototype-sticky.html
- live-examples/js-examples/regexp-prototype-test.html
- live-examples/js-examples/regexp-prototype-tostring.html
- live-examples/js-examples/regexp-prototype-unicode.html
- site.json
I don't necessarily think we should merge this, but I put it out there for discussion.
The issues are:
1. `regexp-prototype-source.html` - specifically:
```
console.log(new RegExp('\n').source === '\\n');
// expected output: true
```
Which I believe should return `true` (source : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/source)
It returns `true` in Firefox and Safari but `false` in Chrome and Opera .
2. `regexp-prototype-tostring.html` - (possibly related to 1.) specifically:
```
console.log(new RegExp('\n', 'g').toString());
// expected output: "/\n/g"
```
This produces the expected output in Firefox and Safari but in Chrome and Opera produces:
```
"/
/g"
```
> JS RegExp examples (with caveats)

- live-examples/css-examples/box-sizing.html
- live-examples/css-examples/css/box-sizing.css
- site.json
I wasn't sure whether to include the `width: 100%` in the "hidden" CSS or explicitly in the example. In the end I included it in the example, because it seems very relevant to this particular property.
> Added an example for box-sizing

- live-examples/css-examples/css/position.css
- live-examples/css-examples/position.html
I was looking at these, and decided the boxes ought to be smaller to make it less likely that they wrap. It still kind of works when they wrap, but it's better if they don't IMO.
But then I also realised that the "sticky" example wasn't very good, because the boxes are already at the top, so the sticky box doesn't scroll at all, so it's just like fixed. So I added a bit of text above, so you can more easily see it working.
> Improvements to the position example

- live-examples/js-examples/array-reduce.html
The first element of the array was missing in the comment of the array reduce example.
> Fixed mistake in array-reduce comment

- live-examples/css-examples/css/opacity.css
- live-examples/css-examples/opacity.html
- site.json
Adding an interactive example for the [opacity](https://developer.mozilla.org/en-US/docs/Web/CSS/opacity) CSS property
> Adding an interactive example for the opacity CSS property

- live-examples/css-examples/css/word-break.css
- live-examples/css-examples/word-break.html
- site.json
Proposing a simple example for the [word-break](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) CSS property
> Adding a CSS interactive example for word-break property

- live-examples/css-examples/css/text-shadow.css
- live-examples/css-examples/text-shadow.html
- site.json
The examples are taken more or less directly from the original page: https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow.
> Add text-shadow example

- CONTRIBUTING.md
- js/editor-libs/mce-utils.js
The current`isPropertySupported` code checks whether the given `dataset` is undefined, and skips the check if it is.
But actually if no `data-` attributes are given, then `dataset` will be an empty map, which will end up making the function return `false`.
This change should instead make the code check whether `dataset` contains a `property` property, and return `true` if it doesn't - so omitting `data-property` means all browsers support it.
I've also updated CONTRIBUTING.md to talk a bit about this attribute.
> Handle omitted data-property attribute

- live-examples/js-examples/math-atan2.html
Small tweak:
Math.atan2 takes parameters in the order `(y, x)`.
I'm updating the example to show that:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/atan2
I think that's how it should be at least 😅
> Fix parameter ordering Math.atan2 example

- site.json
valueof->valueOf
tostring->toString
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toString
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/valueOf
> Fix case in Number example titles

- site.json
Same errors as in https://github.com/mdn/interactive-examples/pull/383, but for Object:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/valueOf
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString
> Fix case in Object example titles

- live-examples/css-examples/css/font-weight.css
- live-examples/css-examples/font-weight.html
- site.json
Added some more options, changed the text to be in line with the other `font` examples. I'm happy to use a different text, if you don't like this one :).
I wonder if we should use common CSS for related examples. I saw there was some work to support this already.
> Update font-weight example

- site.json
`map` -> `Map`
`foreach` -> `forEach`
`keyfor` -> `keyFor`
> fix case for titles

- site.json
Fix title:
`TypedArray.tostring()` -> `TypedArray.toString()`
> Fix case of TypedArray.toString()

- site.json
This adjusts the case of the titles used for ["Expressions and Operators"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators) examples, basically to match the title of the document.
This means:
* preserve case for keywords (`yield` not `Yield`)
* sentence case otherwise (`Operator precedence` not `Operator Precedence`)
I'm happy to discuss this if you disagree, but this seems like the best approach to me.
(I think we should do the same for CSS too - i.e. `box-shadow` not `Box Shadow`.)
> Fix case for titles of Expressions examples

- live-examples/css-examples/sepia.html
- site.json
Shamelessly using the existing `filter` interactive example to create an example for https://developer.mozilla.org/fr/docs/Web/CSS/filter-function/sepia
> Creating an example for the sepia filter function

- CONTRIBUTING.md
- site.json
As discussed in https://github.com/mdn/interactive-examples/pull/412, let's use keywords for titles. I've also updated the docs to talk a little about the `title` property. Note also that one of the titles had the wrong content.
> Fix CSS example titles; update docs

- js/editor-libs/feature-detector.js
- live-examples/js-examples/sharedarraybuffer-bytelength.html
- live-examples/js-examples/sharedarraybuffer-constructor.html
- live-examples/js-examples/sharedarraybuffer-slice.html
@wbamberg This uses the `featureDetector` to disable `SharedArrayBuffer` interactive examples. Currently this is disabled because of Spectre. There is a message about it on the relevant pages. These examples will start working again once browser vendors have resolved the Spectre issue.
Is this worth doing, or do you feel like we should keep the live examples? Currently clicking run will result in a message of:
`Error: SharedArrayBuffer is not defined`
> Disables interactive examples for the currently disabled SharedArrayBuffer

- js/editor-libs/console-utils.js
- js/editor-libs/console.js
such as `console.log('Hello', 'World', '!');`
> console.log support for multiple arguments

- live-examples/css-examples/css/line-height.css
- live-examples/css-examples/line-height.html
- site.json
Fixes: CSS examples: need example for line-height #466
> Add line-height CSS example

- live-examples/css-examples/filter.html
- live-examples/css-examples/font-family.html
- live-examples/css-examples/font-weight.html
- live-examples/css-examples/position.html
- live-examples/css-examples/text-decoration.html
- live-examples/css-examples/text-shadow.html
- live-examples/css-examples/transform.html
Easy to overlook, and I bet someone or myself will be making this oopsie down the road. Maybe should be automated or tested for?
> Fixed some (all?) `data-clipboard-target` for CSS examples

- live-examples/css-examples/css/text-decoration-style.css
- live-examples/css-examples/text-decoration-style.html
- site.json
Fixes: #478 reusing some code from `text-decoration`. `text-decoration-line: underline;` is added via CSS file and not shown per [CSS-Example-Style-Guide > Multiple declarations](https://github.com/mdn/interactive-examples/blob/master/CSS-Example-Style-Guide.md#multiple-declarations).
> Add text-decoration-style CSS example

- live-examples/css-examples/css/text-decoration-line.css
- live-examples/css-examples/text-decoration-line.html
- site.json
Fixes: #477 reusing some code from `text-decoration`. Didn't include deprecated `blink` and set `underline` as the default.
> Add text-decoration-line CSS example

- js/editor-libs/clippy.js
addClippy will now construct a Clipboard where it finds the example code
Still can be overwritten by using a `data-clipboard-target` attribute, but that's no longer necessary.
Fixes: Test or automate `data-clipboard-target` #489
> Dynamically get clipboard button targets

- live-examples/css-examples/background-clip.html
- live-examples/css-examples/css/background-clip.css
Some updates to this example:
* use an image instead of a solid color, as it's a bit more interesting
* add the `text` value (this also needs the `-webkit` prefixed version)
* use a dashed border instead of dotted (looks a bit better IMO)
* slightly reworded the text.
> Updates to background-clip example

- live-examples/css-examples/border-bottom-width.html
- live-examples/css-examples/border-left-width.html
- live-examples/css-examples/border-right-width.html
- live-examples/css-examples/border-top-width.html
- live-examples/css-examples/css/border-width.css
- site.json
Also updates the basic `border-width` example to be a little prettier and illustrate the three-value syntax. Fixes #496.
> Add `border-*-width` examples

- live-examples/css-examples/css/overflow.css
- live-examples/css-examples/overflow-x.html
- live-examples/css-examples/overflow-y.html
- live-examples/css-examples/overflow.html
- site.json
Adds `overflow`, `overflow-x`, and `overflow-y` examples. Fixes #470.
> Add `overflow-*` examples

- index.js
Also TIL that the 2nd argument at String.prototype.replace has special handling of dollar signs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter
Fixes #313
> Fix dollar sign messing up template replacement

- CONTRIBUTING.md
- CSS-Example-Style-Guide.md
A couple of docs updates:
* how to reference media from CSS. This should I think enable us to close https://github.com/mdn/interactive-examples/issues/344
* output width considerations
> 2 small docs updates

- live-examples/css-examples/multi-column-layout/column-count.html
- live-examples/css-examples/multi-column-layout/column-fill.html
- live-examples/css-examples/multi-column-layout/column-gap.html
- live-examples/css-examples/multi-column-layout/column-rule-color.html
- live-examples/css-examples/multi-column-layout/column-rule-style.html
- live-examples/css-examples/multi-column-layout/column-rule-width.html
- live-examples/css-examples/multi-column-layout/column-rule.html
- live-examples/css-examples/multi-column-layout/column-width.html
- live-examples/css-examples/multi-column-layout/columns.html
Remove IDs from the `columns` examples, [whose PR](https://github.com/mdn/interactive-examples/pull/549) was in flight when https://github.com/mdn/interactive-examples/pull/556 landed.
> Remove redundant IDs

- live-examples/js-examples/classes/classes-extends.html
- live-examples/js-examples/function/function-bind.html
- live-examples/js-examples/number/number-isnan.html
- live-examples/js-examples/proxyhandler/proxyhandler-apply.html
- live-examples/js-examples/proxyhandler/proxyhandler-construct.html
- live-examples/js-examples/proxyhandler/proxyhandler-defineproperty.html
- live-examples/js-examples/proxyhandler/proxyhandler-get.html
- live-examples/js-examples/proxyhandler/proxyhandler-getownpropertydescriptor.html
- live-examples/js-examples/proxyhandler/proxyhandler-getprototypeof.html
- live-examples/js-examples/proxyhandler/proxyhandler-has.html
- live-examples/js-examples/proxyhandler/proxyhandler-isextensible.html
- live-examples/js-examples/proxyhandler/proxyhandler-ownkeys.html
- live-examples/js-examples/proxyhandler/proxyhandler-preventextensions.html
- live-examples/js-examples/proxyhandler/proxyhandler-set.html
- live-examples/js-examples/reflect/reflect-deleteproperty.html
- live-examples/js-examples/reflect/reflect-isextensible.html
- live-examples/js-examples/regexp/regexp-prototype-multiline.html
- live-examples/js-examples/regexp/regexp-prototype-test.html
- live-examples/js-examples/regexp/regexp-prototype-tostring.html
- live-examples/js-examples/regexp/regexp-prototype-unicode.html
- live-examples/js-examples/weakset/weakset-prototype-add.html
Fixes https://github.com/mdn/interactive-examples/issues/464.
This should add `data-height="taller"` to all the examples listed in https://github.com/mdn/interactive-examples/issues/464#issuecomment-360625731, except for these three examples, that already have it:
```
proxyhandler-setprototypeof
proxyhandler-deleteproperty
statement-async
```
> Add 'taller' to taller JS examples

- live-examples/css-examples/basic-user-interface/meta.json
- live-examples/css-examples/basic-user-interface/resize.css
- live-examples/css-examples/basic-user-interface/resize.html
https://github.com/mdn/interactive-examples/issues/581
Added examples for `both`, `horizontal`, `vertical`, and `none` values.
---
> Add resize example

- css/editable-css.css
Sometimes CSS code examples overflow horizontally, When this happens, part of the code is covered by the copy button. For example, see https://developer.mozilla.org/en-US/docs/Web/CSS/background-image.
To fix this, this PR adds some more padding to the right side of the `<pre>` elements.
> Increase padding for code area

- live-examples/css-examples/lists/list-style-type.html
- live-examples/css-examples/lists/list-style.css
- live-examples/css-examples/lists/meta.json
This PR adds an example for the [`list-style-type`](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type) CSS property. This is my first attempt at an example (🎉) so I'm open to any and all input on this. One area in particular I'm concerned about is the appearance of the `@counter-style` definition.
This ought to fix #483 (which looked unclaimed to me, at the moment).
> Add example for list-style-type CSS property

- live-examples/css-examples/lists/list-style-type.html
- live-examples/css-examples/lists/list-style.css
Following up from the conversation on #594, this removes the complicated description of `@counter-style` in the `list-style-type` example.
> Clean up appearance of list-style-type example

- CONTRIBUTING.md
This PR adds a section to the contributing guide on how to embed an example on a page. I figured it would be nice to have it spelled out somewhere.
> Document publishing an example on a wiki page

- css/tabbed-editor.css
When they're embedded in MDN pages, the editors get a gray background. With the HTML editor, the output isn't given its own background, so it's not clear that the output is a distinct section:
This PR adds a white background-color, and a bit of margin, to the output, so it should look like:
It could probably use some refinement :) but should be an improvement. Let me know what you think!
> Add background color for output

- live-examples/css-examples/basic-box-model/clear.css
- live-examples/css-examples/basic-box-model/float.css
The examples for [`float`](https://developer.mozilla.org/en-US/docs/Web/CSS/float) and [`clear`](https://developer.mozilla.org/en-US/docs/Web/CSS/clear) overflow vertically quite easily. For example, here's what `float` looks like on my screen, full-width but with a sidebar open (tree-style tabs):
This PR reduces line-height for these examples. Here's what `float` looks like at the same width, with this change:
> reduce line-height for float and clear

- lib/pageBuilder.js
Currently the page builder [returns after finding the first "tabbed" entry in meta.json](https://github.com/mdn/interactive-examples/blob/master/lib/pageBuilder.js#L44), meaning any entries after the first are ignored.
This PR changes that so we keep going, so if meta.json contains more than one tabbed example, they all get processed.
(I'm not sure if this is right, maybe there's some reason to only allow one? But anyway this change seems to work to allow us to have > 1.)
> Allow more than one tabbed example

- css/tabbed-editor.css
In the current implementation the width of the editor can change when the user switches tabs:
I think this is distracting. This PR is supposed to make the width fixed, so editor and output each get 50%, no matter what:
This seems better to me, but I'm open to other ideas...
> HTML editor: make editor width fixed

- live-examples/css-examples/animation/animation-fill-mode.css
- live-examples/css-examples/animation/animation-fill-mode.html
- live-examples/css-examples/animation/animation-fill-mode.js
- live-examples/css-examples/animation/meta.json
This PR adds an example for [`animation-fill-mode`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-fill-mode).
I think this might still be a work in progress. It's quite difficult to show the relationship between the mode and the animation without a lot of context for the animation itself (particularly the animation delay). I'm open to ideas on how to improve this. Let me know if you have any suggestions. Thanks!
> Add example for animation-fill-mode CSS property

- live-examples/css-examples/basic-user-interface/caret-color.css
- live-examples/css-examples/basic-user-interface/caret-color.html
- live-examples/css-examples/basic-user-interface/meta.json
This PR adds an example for [`caret-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/caret-color). Let me know if you want to see any changes. Thanks!
> Add example for CSS caret-color property

- live-examples/css-examples/lists/counter-increment.css
- live-examples/css-examples/lists/counter-increment.html
- live-examples/css-examples/lists/counter-reset.css
- live-examples/css-examples/lists/counter-reset.html
- live-examples/css-examples/lists/meta.json
This PR adds examples for [`counter-reset`](https://developer.mozilla.org/en-US/docs/Web/CSS/counter-reset) and [`counter-increment`](https://developer.mozilla.org/en-US/docs/Web/CSS/counter-increment). Let me know if you want to see any changes. Thanks!
> Add examples for counter-reset and counter-increment

- live-examples/css-examples/svg/meta.json
- live-examples/css-examples/svg/pointer-events.css
- live-examples/css-examples/svg/pointer-events.html
This PR adds an example for [`pointer-events`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events). Let me know if you want to see any changes. Thanks!
> Add example for CSS pointer-events property

- css/tabbed-editor.css
This gives the editor tabs 60% of the width, as they seem generally to need it more than the output ([60% is also the width given to the example-choice-list for the CSS examples](https://github.com/mdn/interactive-examples/blob/master/css/editable-css.css#L14)).
> Give the editor a little more space

- live-examples/css-examples/animation/animation-fill-mode.html
- live-examples/css-examples/basic-user-interface/caret-color.html
- live-examples/css-examples/fonts/font-weight.html
- live-examples/css-examples/lists/list-style-image.html
- live-examples/css-examples/lists/list-style-type.html
This fixes the CSS examples which have `data-property` set to something that's not the name of the property being demonstrated, or the camel case form of the same name (e.g., for `animation-fill-mode` I would've left either value `animation-fill-mode` or `animationFillMode`, but `animation` was wrong).
> Fix mismatched data-property values

- live-examples/css-examples/backgrounds-and-borders/background-attachment.css
- live-examples/css-examples/backgrounds-and-borders/background-attachment.html
It's a shame that the [background-attachment example](https://developer.mozilla.org/en-US/docs/Web/CSS/background-attachment) doesn't distinguish between `scroll` and `fixed` (compare, for example, https://codepen.io/tjacobdesign/pen/wBeXZz). I had hoped it would work, but it doesn't, presumably because it's in an iframe.
This PR makes the container scroll, so if you scroll the container, you can see the difference between the two values. What do you think, @mfluehr ? Maybe there's a better approach?
> Make container scroll for background-attachment example

- live-examples/css-examples/images/meta.json
- live-examples/css-examples/images/object-position.css
- live-examples/css-examples/images/object-position.html
This PR adds an example for [`object-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position). Let me know if you want to see any changes. Thanks!
> Add example for object-position CSS property

- live-examples/css-examples/text/meta.json
- live-examples/css-examples/text/text-align-last.css
- live-examples/css-examples/text/text-align-last.html
This PR adds an example for [`text-align-last`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align-last). Let me know if you want to see any changes. Thanks!
> Add example for text-align-last CSS property

- live-examples/css-examples/text/meta.json
- live-examples/css-examples/text/text-indent.css
- live-examples/css-examples/text/text-indent.html
This PR adds an example for [`text-indent`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-indent). Let me know if you want to see any changes. Thanks!
> Add example for text-indent CSS property

- live-examples/js-examples/object/object-create.html
The previous version worked just the same even when deleting the line which had Object.create in it!
Also, this version seems simpler to me, as it does not assume knowledge of functions as constructors and the new keyword, etc.
This version however assumes (teaches?) knowledge about the context of inherited methods. It could of course be even simpler, if we just leave out the sayName method and focus on primitive inherited fields.
> Rewrite the Object.create example.

- live-examples/js-examples/statement/statement-trycatch.html
Errors should be displayed using the console.error() method.
> Use console.error() method to display errors

- live-examples/css-examples/images/image-rendering.css
- live-examples/css-examples/images/image-rendering.html
- live-examples/css-examples/images/meta.json
This PR adds an example for [`image-rendering`](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering), though I think it might still be a work in progress. The main issue here is that it's hard to show this property in action without using vendor prefixes on the values, but I think that would really complicated the example. Any advice on how to improve this one would be appreciated. Thanks!
> Add example for image-rendering CSS property

- live-examples/css-examples/fonts/font-variant-caps.css
- live-examples/css-examples/fonts/font-variant-caps.html
- live-examples/css-examples/fonts/font-variant.css
- live-examples/css-examples/fonts/font-variant.html
- live-examples/css-examples/fonts/fonts.css
- live-examples/css-examples/fonts/meta.json
This PR adds an example for [`font-variant`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant) and [`font-variant-caps`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-caps). Let me know if you want to see any changes. Thanks!
> Add examples for font-variant and font-variant-caps CSS property

- live-examples/css-examples/text-decoration/meta.json
- live-examples/css-examples/text-decoration/text-underline-position.css
- live-examples/css-examples/text-decoration/text-underline-position.html
This PR adds an example for [`text-underline-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-position). I got far along with this before realizing that the property is not particularly well-supported (works in Chrome, not so much elsewhere), but since it was finished I figured I should offer it up anyway. Let me know if you want to see any changes (but I'm also OK with not merging it too). Thanks!
> Add example for text-underline-position CSS property

- live-examples/css-examples/compositing-and-blending/isolation.css
- live-examples/css-examples/compositing-and-blending/isolation.html
- live-examples/css-examples/compositing-and-blending/meta.json
This PR adds an example for [`isolation`](https://developer.mozilla.org/en-US/docs/Web/CSS/isolation). Let me know if you want to see any changes. Thanks!
> Add example for isolation CSS property

- live-examples/css-examples/text/meta.json
- live-examples/css-examples/text/tab-size.css
- live-examples/css-examples/text/tab-size.html
This PR adds an example for [`tab-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size). It's probably easiest to try this out in Chrome. Let me know if you want to see any changes. Thanks!
> Add example for tab-size CSS property

- live-examples/css-examples/scroll-snap/meta.json
- live-examples/css-examples/scroll-snap/scroll-snap-type.css
- live-examples/css-examples/scroll-snap/scroll-snap-type.html
Here is an example for scroll-snap-type. For the new spec so only works in Safari. Building this highlights various issues in the MDN docs for scroll-snapping.
We have all the properties now removed from the spec (but supported by Firefox), we don't have scroll-snap-align. The current example on the scroll-snap-type page is incorrect now as to the updated spec, although uses the properties as supported by Firefox. It looks like the browser information is incorrect too.
Quite difficult to know what to do with these specs which have a bit of implementation but then change in a major way.
> Scroll snapping

- live-examples/css-examples/fonts/fonts-base.css
- live-examples/css-examples/text/text-align-last.html
The [`text-align-last`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align-last) example can overflow vertically, cutting off the last line so the effect is not visible:
This PR reduces the size of the text sample so that doesn't happen. It also fixes the width of the text `div`, so that we can make the effect more predictable (with a variable width output, the effect was more or less obvious depending on the browser window width). This change also affects [`text-align`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align) since they share a CSS file, but also for the better I think.
> Reduce text size example; fix width

- live-examples/css-examples/transforms/meta.json
- live-examples/css-examples/transforms/transform-style.css
- live-examples/css-examples/transforms/transform-style.html
This PR adds an example for [`transform-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-style). This is kinda a tough one to illustrate. Let me know if you want to see any changes. Thanks!
> Add example for transform-style CSS property

- live-examples/css-examples/fonts/font-variant-caps.css
- live-examples/css-examples/fonts/font-variant.css
The fonts aren't loading on these new examples. It seems that the paths specified in the CSS work for the local dev server, but not as deployed. This PR should fix that. Let me know if you want to see any changes! Thanks!
> Fix broken fonts in font-variant and font-variant-caps examples

- live-examples/css-examples/text/meta.json
- live-examples/css-examples/text/text-justify.css
- live-examples/css-examples/text/text-justify.html
This PR adds an example for [`text-justify`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-justify). I think this one works pretty well for now, though like #651, I think it might benefit from some added CJK text to show the inter-character spacing option a bit better (though that could come in a later PR). Let me know if you want to see any changes. Thanks!
> Add example for text-justify CSS property

- live-examples/css-examples/fonts/font-feature-settings.css
- live-examples/css-examples/fonts/font-feature-settings.html
- live-examples/css-examples/fonts/meta.json
This PR adds an example for [`font-feature-settings`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings). If this looks like a clone of `font-variant` that's because it is—it does almost the exact same thing, with a different syntax. Let me know if you want to see any changes. Thanks!
> Add example for font-feature-settings CSS property

- live-examples/css-examples/cssom-view/meta.json
- live-examples/css-examples/cssom-view/scroll-behavior.css
- live-examples/css-examples/cssom-view/scroll-behavior.html
This PR adds an example for [`scroll-behavior`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior). The only thing I was uncertain about here was the directory; the spec says it's likely to move to a different spec, so I'm not sure it actually deserves its own directory. Let me know if you want to see any changes. Thanks!
> Add example for scroll-behavior

- live-examples/css-examples/basic-user-interface/appearance.html
- live-examples/css-examples/basic-user-interface/meta.json
This PR adds [`-moz-appearance`](https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-appearance). This one's experimental and not-well supported yet, but it was on the to-do list so I did a pretty minimal example here. Let me know if you want to see any changes. Thanks!
> Add example for (-moz-) appearance CSS property

- live-examples/css-examples/fonts/font-kerning.css
- live-examples/css-examples/fonts/font-kerning.html
- live-examples/css-examples/fonts/meta.json
Trying this again. There seems to be some odd line endings in `css-examples/fonts/meta.json`; I've ignored them for now but you may want to check that out.
> Add example for CSS font-kerning property

- live-examples/css-examples/animation/animation-iteration-count.css
- live-examples/css-examples/animation/animation-iteration-count.html
- live-examples/css-examples/animation/meta.json
This PR adds an example for [`animation-iteration-count`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-iteration-count). Let me know if you want to see any changes. Thanks!
> Add example for animation-iteration-count CSS property

- live-examples/css-examples/fonts/font-language-override.css
- live-examples/css-examples/fonts/font-language-override.html
- live-examples/css-examples/fonts/meta.json
This PR adds an example for [`font-language-override`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-language-override). Let me know if you want to see any changes. Thanks!
> Add example for font-language-override CSS property

- live-examples/css-examples/grid/grid-gap.html
See also MDN changes: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-gap$compare?locale=en-US&to=1367223&from=1359654
> Update: add calc() values in grid-gap demo

- live-examples/css-examples/animation/animation-name.css
- live-examples/css-examples/animation/animation-name.html
- live-examples/css-examples/animation/meta.json
This PR adds an example for [`animation-name`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-name). Let me know if you want to see any changes. Thanks!
> Add example for animation-name CSS property

- .eslintrc.js
- .prettierrc
- .travis.yml
- __tests__/puppeteer-js-editor.test.js
- jest-puppeteer.config.js
- package-lock.json
- package.json
Run: `npm install` to get new dependencies, then
Run: `npm run unit-tests`
Note to Self: Change `unit-tests` to just be `test` as this now runs unit and functional tests
> Adds the groundwork for puppeteer tests and on test for the js editor

- live-examples/js-examples/proxyhandler/proxyhandler-apply.html
IMO, the original example is somewhat lackluster.
In the existing example, the proxied `proxy1` function returns the same result as the original `sum` function; both return the sum of `arguments[0]` and `arguments[1]`. Th me, this seems pointless and does not do a proper job of showing how useful `Proxy` can be.
I think it would be best to show how `Proxy.apply` can be used to intercept and modify the return value and/or parameters passed to the target function.
Interested in everybody's thoughts. Thanks.
> More illustrative example for `Proxy.apply`

- live-examples/css-examples/writing-modes/meta.json
- live-examples/css-examples/writing-modes/text-orientation.html
This PR adds an example for [`text-orientation`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation). I think this one is OK, though there is one other value, `sideways-right` we could show, but that's only meaningful if there's a mix of vertical and horizontal characters (e.g., a mix of Latin and Japanese characters). Let me know if you want to see any changes. Thanks!
> Add example for text-orientation CSS property

- live-examples/css-examples/fonts/font-variant-ligatures.css
- live-examples/css-examples/fonts/font-variant-ligatures.html
- live-examples/css-examples/fonts/font-variant-numeric.css
- live-examples/css-examples/fonts/font-variant-numeric.html
- live-examples/css-examples/fonts/meta.json
This PR adds examples for [`font-variant-ligatures`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures) and [`font-variant-numeric`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric). Let me know if you want to see any changes. Thanks!
> Add examples for font-variant-ligatures and font-variant-numeric

- live-examples/js-examples/arraybuffer/meta.json
Remove the parens because it's not a function but a number.
> Fix: ArrayBuffer.byteLength() => byteLength

- css/tabbed-editor.css
- tmpl/live-tabbed-tmpl.html
@wbamberg This is what it looks like in the context of a MDN page:
> Fix issue #690, add output label to tabbed editor output pane

- live-examples/css-examples/text-decoration/meta.json
- live-examples/css-examples/text-decoration/text-emphasis-color.css
- live-examples/css-examples/text-decoration/text-emphasis-color.html
- live-examples/css-examples/text-decoration/text-emphasis-style.css
- live-examples/css-examples/text-decoration/text-emphasis-style.html
- live-examples/css-examples/text-decoration/text-emphasis.css
- live-examples/css-examples/text-decoration/text-emphasis.html
This PR adds examples for:
* [`text-emphasis`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis)
* [`text-emphasis-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-color)
* [`text-emphasis-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-style)
I'm mostly satisfied with how these have turned out except for one thing: these emphasis marks aren't really intended for Latin script, but I don't really know any Japanese or Chinese text to use as an example. Open to suggestions there or on anything else. Thanks!
> Add examples for text-emphasis CSS properties

- js/editor-libs/css-editor-utils.js
Reading the code, the previous behavior includes the text "Copy to clipboard" at `code` parameter of `applyCode` of `css-editor-utils.js`. 
So, for example, at [text-decoration-color example](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color), when switching to the option `text-decoration-color: #21ff21;`, the value of `code` parameter will be as follows
```
text-decoration-color: #21ff21;
Copy to clipboard
```
It doesn't cause any bug though, as somehow, `element.style.cssText` only applies the first line of `code` argument.
I submits this PR, because I think it is not the intended behavior. 😁 
Note: to see this "bug", you could put `console.log(code)` before `element.style.cssText = code;` line
> Apply code in code block instead of choice element

- css/tabbed-editor.css
- js/editor-libs/tabby.js
Wraps long lines in HTML editor. Fixes https://github.com/mdn/interactive-examples/issues/699
> Tabbed editor wrap long lines

- live-examples/css-examples/backgrounds-and-borders/box-shadow.css
Hard-coded 'height' is bad web design because they cause bugs like these:
https://bugzilla.mozilla.org/show_bug.cgi?id=1453903
> Remove hard-coded 'height'

- live-examples/html-examples/inline-text-semantics/css/kbd.css
- live-examples/html-examples/inline-text-semantics/kbd.html
- live-examples/html-examples/inline-text-semantics/meta.json
Hello, this is my first contribution to this repo.
Example for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd
> Add <kbd> example

- CONTRIBUTING-HTML.md
- lib/pageBuilderUtils.js
- live-examples/html-examples/content-sectioning/meta.json
- live-examples/html-examples/forms/meta.json
- live-examples/html-examples/image-and-multimedia/meta.json
- live-examples/html-examples/inline-text-semantics/meta.json
- live-examples/html-examples/table-content/meta.json
- live-examples/html-examples/text-content/meta.json
It is no longer necessary to manually escape the `<` inside title in `meta.json`. This is no automatically done as part of the build. I also updated all the existing meta.json files as well as the documentation.
> fix: issue #774, escape < in page titles

- live-examples/html-examples/forms/css/form.css
- live-examples/html-examples/forms/form.html
- live-examples/html-examples/forms/meta.json
as per https://github.com/mdn/interactive-examples/issues/746.
However, there are two problems with this example, one minor and one major:
* Minor: I had to add some extraneous classes to namespace the block elements in my example, otherwise my CSS was clashing with the styling of the editor UI, and messing things up. How I've got it now is not ideal, but it's working.
* Major: I think it must be because there's a form in the example, but whenever I click on the CSS, it seems to submit the form and therefore refresh the page, meaning you can't see or edit the CSS. I tried adding some preventDefault() code inline on the form element, but this didn't seem to work either. It makes me think that this is probably going to be a problem with any example that features a form element. Could you …
> adding form element example

- live-examples/html-examples/inline-text-semantics/css/data.css
- live-examples/html-examples/inline-text-semantics/data.html
- live-examples/html-examples/inline-text-semantics/meta.json
Example for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/data
This demo would work better with some JavaScript interaction (I think) as that seems to be the main use case for the `<data>` element. I did some CSS voodoo instead, let me know if that isn't suitable here.
Fixes #770
> Add <data> example

- live-examples/html-examples/text-content/css/dl.css
- live-examples/html-examples/text-content/dl.html
- live-examples/html-examples/text-content/meta.json
Simple interactive example for `<dl>`.  Probably will use modifications of this same code for `<dt>` and `<dd>` -- but not the exact same example, because that can mess up SEO.
> Add interactive example for dl element

- live-examples/html-examples/table-content/meta.json
https://github.com/mdn/interactive-examples/pull/821 unintentionally removed the meta.json entry for `<caption>`. This PR puts it back.
> Reinstate caption in meta.json

- live-examples/html-examples/demarcating-edits/css/ins.css
- live-examples/html-examples/demarcating-edits/ins.html
- live-examples/html-examples/demarcating-edits/meta.json
Fixes #736.
CSS got a little longer (35 lines) mainly because of the `+/-` decoration. Previously, in the `<del>` example, I used them as inline level and here I want them to use as block level.
I could remove the  `+/-` prefixes (which uses 15 lines of css), but it won't look as nice as it is now. Let me know what do you think.
> Add <ins> example

- live-examples/html-examples/inline-text-semantics/css/var.css
- live-examples/html-examples/inline-text-semantics/meta.json
- live-examples/html-examples/inline-text-semantics/var.html
Example for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/var
Fixes #815
> Add <var> example

- live-examples/html-examples/inline-text-semantics/css/span.css
- live-examples/html-examples/inline-text-semantics/meta.json
- live-examples/html-examples/inline-text-semantics/span.html
Example for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/span
Not sure if this is a nice example, but the idea is that I want to show `<span>` as a re-usable, inline, styled element in text content. In this case it is something like a banner.
Fixes #788
> Add <span> example

- live-examples/html-examples/inline-text-semantics/css/wbr.css
- live-examples/html-examples/inline-text-semantics/meta.json
- live-examples/html-examples/inline-text-semantics/wbr.html
Example for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr
`&shy;` isn't shown in the source view as is, but displayed as a red dot for me. I thought it would be nice to compare it, though. Another idea was to compare to `<br>` but I thought that might be too obvious.
I believe a `wbr { }` CSS selector isn't needed here.
Fixes #816
> Add <wbr> example

- live-examples/html-examples/text-content/css/li.css
- live-examples/html-examples/text-content/li.html
- live-examples/html-examples/text-content/meta.json
Example for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li
I thought it would be nice to show `<li>` with both `<ol>` and `<ul>`. So this is nested again. It's a little uncreative when comes to the CSS, let me know if I should try harder to make it more fancy.
> Add <li> example

- live-examples/js-examples/date/date-valueof.html
Fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1459457
> Fix typo n Date.valueOf example (bug 1459457)

- live-examples/html-examples/document-metadata/css/style.css
- live-examples/html-examples/document-metadata/meta.json
- live-examples/html-examples/document-metadata/style.html
Example for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style
The idea here is to show the order of precedence. (which I would have expected to be documented on that page btw).
Fixes #738
> Add <style> example

- live-examples/html-examples/input/css/input.css
- live-examples/html-examples/input/input.html
- live-examples/html-examples/input/meta.json
> Add Input ~ input example

- live-examples/html-examples/content-sectioning/css/nav.css
- live-examples/html-examples/content-sectioning/meta.json
- live-examples/html-examples/content-sectioning/nav.html
Example for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav
Just a classic breadcrumb navigation inspired by MDN itself.
Fixes https://github.com/mdn/interactive-examples/issues/733
> Add <nav> example

- live-examples/js-examples/array/array-values.html
- live-examples/js-examples/array/meta.json
First time here. Starting with a simple one :)
Hope to contribute more :)
> Add Array.prototype.values()

- live-examples/css-examples/backgrounds-and-borders/background-clip.css
- live-examples/css-examples/backgrounds-and-borders/background-origin.html
Adding a no-repeat property makes the example clearer because it shows the effect of the background-origin property on the the extent of background image. Before and after images below:
> Added no-repeat property for background-origin example.

- live-examples/js-examples/string/meta.json
- live-examples/js-examples/string/string-trim.html
- live-examples/js-examples/string/string-trimend.html
- live-examples/js-examples/string/string-trimstart.html
I am a little puzzled why there are no String examples yet... Did we decide against doing live examples for String or is this an oversight? 
Anyway, here is my first JS examples PR that creates examples for:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimStart
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimEnd
> Add String trim examples

- live-examples/html-examples/interactive-elements/css/details.css
- live-examples/html-examples/interactive-elements/details.html
- live-examples/html-examples/interactive-elements/meta.json
No github issue created so far.
I added some more styles to the element to make clear that it is a fully customizable element.
> Add HTML example for <details>

- live-examples/html-examples/interactive-elements/css/summary.css
- live-examples/html-examples/interactive-elements/meta.json
- live-examples/html-examples/interactive-elements/summary.html
The merge will potentially fail, when #924 is merged before, because I created a new directory for the interactive elements.
I created a slightly simpler example compared to my `<details>` example.
I can surely do a rebase and fix the merge conflicts if #924 is merged before.
> Add HTML example for <summary>

- live-examples/html-examples/image-and-multimedia/audio.html
I added text for non-supporting browsers and a second `audio` element to demo `loop` and the `source` element. (OK, and a sad little intro joke...)
> Add HTML example for <audio>

- live-examples/js-examples/object/meta.json
- live-examples/js-examples/object/object-keys.html
This is the edited version of a previous `Pull Request` #725 
It contains:
- `object-keys.html` page
- `objectkeys` object in `meta.json`
_I've tried to update the previous Pull Request, but I couldn't. That's why I created a new one._
> Add object-keys.html

- live-examples/html-examples/text-content/css/figcaption.css
- live-examples/html-examples/text-content/figcaption.html
- live-examples/html-examples/text-content/meta.json
Take a look. I used few lines of HTML and 22 lines of CSS — a little bit of scrolling won't hurt.
> Implemented example for <figcaption> tag

- live-examples/js-examples/math/math-round.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1462897
The demo for Math.round currently implements custom function which performs round in the specified precision, but it's not good function.
Then, the MDN page [1] was describing the issue of the demo, and solution for the function in the demo, instead of the Math.round function itself.
it was completely unrelated to the API and IMO those things shouldn't be on the document,
but the document should describe the API itself.
Changed the demo to directly use the Math.round.
also I've removed the unrelated sections from the MDN [2].
[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round
[2] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round$compare?locale=en-US&to …
> Bug 1462897 - Directly use Math.round in the demo code.

- __tests__/console-utils.test.js
- js/editor-libs/console-utils.js
Fixes #952 
The bug is caused by using [`String(value)` function](https://www.ecma-international.org/ecma-262/6.0/#sec-string-constructor-string-value), which per the spec calls [`ToString(value)`](https://www.ecma-international.org/ecma-262/6.0/#sec-tostring). _ToString(value)_ for number as per defined [at the spec](https://www.ecma-international.org/ecma-262/6.0/#sec-tostring-applied-to-the-number-type) states that
> Number m to String format as follows:
> 2.  If m is +0 or −0, return the String "0".
So, this PR adds the case where if we meet negative zero at `formatOutput`, then return `-0`, else call `String(input)`. Also, more tests are added.
> Fix console util to support negative zero

- live-examples/css-examples/fonts/font-style.css
- live-examples/css-examples/fonts/font-style.html
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1436048
The example also now uses an open type font. I added this because the oblique angle values don't seem to work with normal fonts.
> adding oblique plus angle option to font-style example

- live-examples/css-examples/box-alignment/place-content.html
The one-value syntax works in most browsers (I verified in Firefox/Chrome/Safari), so we should include a demo of it.
> Add one-value example for place-content

- js/editable-css.js
- js/editable-js.js
- js/editor-libs/mce-utils.js
- js/editor.js
@tkadlec This will post a message to Kuma to set a custom mark at the same time as we send `performance.timing.loadEventEnd` for GA beaconing.
On the Kuma side I will then also set a new custom mark in the head of the pages similar to https://github.com/mdn/interactive-examples/blob/master/js/editor-libs/perf.js#L18
I will then also set a new measure which will use the mark from the head in Kuma as `startMark` and then the mark we are creating here as `endMark`. That should then give us the duration equal to `ie-load-complete`
Let me know your thoughts. Thanks!
> fix(performance): send post to kuma for custom ie-load-event-end metric

- live-examples/html-examples/content-sectioning/address.html
The description for the [`<address>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address) element says:
> … It should include the name of the person, people, or organization to which the contact information refers.
This PR adds a name to make it clear that one should be added.
> fix(address): add name to the provided address

- js/editor-libs/mce-utils.js
- js/editor.js
I added two helper functions that are called inside the editor's `render` method.
`openLinksInNewTab` prevents the default click event on external links (all anchors with an `href` attribute that starts with `http`) and opens them in a new tab.
While I was at it, I stumbled upon the issue that relative links (like `<a href="#someanchor">`) also didn't work. I didn't find a ticket for that so I thought it would make sense to fix in the scope of this ticket.
`scrollToAnchors` prevents the default click event on relative links and scrolls the targeted anchor into view.
I hope that the code structure adheres to your quality standards.
> Issue#946 open links in new tab

- js/editor.js
**Problem:** Calling `removeChild` on a non-child node throws an error.
**Fix:** The cheap solution here is to delete the content coming from the HTML editor first, then query all remaining `<style>` elements (coming from CSS editor and output base styles) and remove them from shadow root.
> Issue #1013 <style> elements in HTML editor break editor's render method

- live-examples/css-examples/color/color-adjust.css
- live-examples/css-examples/color/color-adjust.html
- live-examples/css-examples/color/meta.json
Adds color-adjust interactive example.
> Add color-adjust property example

- live-examples/html-examples/input/password.html
- live-examples/html-examples/input/text.html
Attributes are case-insensitive, and they are conventionally written
in lowercase to reduce confusion.
It seems this particular example accidentally used the naming of
the IDL property (which is different from the DOM attribute).
In most cases the only difference is the casing, but in some cases
(such as node.className vs "class"), the name is different entirely.
In general to avoid confusion, attributes should consistently be
written in lowercase.
> html/input: Lowercase attributes

- .github/config.yml
It seems that the bot's messages are not well formated. My guess is, like in trello, it needs a new line between paragraph and bullet list.
> Add a new line for markdown bullet list

- live-examples/html-examples/document-metadata/link.html
- live-examples/html-examples/document-metadata/meta.json
- media/examples/link-element-example.css
This addresses issue #737 with an example loading an external stylesheet via `<link>`.
> Add example for <link>

- live-examples/css-examples/multi-column-layout/column-fill.html
This may not be necessary so feel free to reject the PR.
Since this property only has 3 values, added the third value of balance-all, which looks exactly like balance. But this might be good to show learners.
> added balance-all value to example

- live-examples/html-examples/inline-text-semantics/css/rb.css
- live-examples/html-examples/inline-text-semantics/meta.json
- live-examples/html-examples/inline-text-semantics/rb.html
Noticed we were missing a page on `<rb>` while looking at our Ruby docs. This is part if it.
Related to https://github.com/mdn/sprints/issues/247
> adding rb element example

- live-examples/html-examples/inline-text-semantics/bdi.html
- live-examples/html-examples/inline-text-semantics/bdo.html
- live-examples/html-examples/inline-text-semantics/css/bdi.css
- live-examples/html-examples/inline-text-semantics/css/bdo.css
- live-examples/html-examples/inline-text-semantics/meta.json
As part of the final set of HTML interactive examples (https://github.com/mdn/interactive-examples/issues/999), I've written some examples for `<bdi>` and `<bdo>`.
Note that Florian already attemped these in https://github.com/mdn/interactive-examples/pull/880. I wasn't sure if there was a good way for me to add onto his PR, so I've just created a new one.
> bdi and bdo interactive examples

- live-examples/html-examples/global-attributes/accesskey.html
- live-examples/html-examples/global-attributes/css/accesskey.css
- live-examples/html-examples/global-attributes/meta.json
As per https://github.com/mdn/sprints/issues/292, I have started adding interactive examples for HTML global attributes. This one covers accesskey.
Although there is one problem with this example — when I tested it locally, it worked fine in Firefox, Chrome, Safari, and Opera. 
In the interactive example version, it doesn't work in Firefox only. Very strange.
> adding accesskey global attribute interactive example

- live-examples/html-examples/embedded-content/picture.html
Replaced the two images used in this example with CC0
ones and removed the attribution. Part of issue #997.
> Use CC0 images in <picture> example

- lib/pageBuilderUtils.js
Tell ``uglify-es`` to turn off the sequences optimization, which joins the top-level statements with a comma instead of a semicolon. This is a wild guess for a fix for Chrome skipping a statement on reload, when the minified JS is injected into a ``<head>`` ``<script>`` element.
Here's the current performance code, beautified:
```js
"use strict";
function postToKuma(e) {
window.parent.postMessage(e, "https://developer.mozilla.org")
}
postToKuma({
markName: "interactive-editor-loading"
}), document.addEventListener("readystatechange", function(e) {
switch (e.target.readyState) {
case "interactive":
postToKuma({
markName: "interactive-editor-interactive",
measureName: "ie-time-to-interactive",
startMark: "interactive-editor-loading",
endMark: "interactive-editor-interactive"
});
break;
case …
```
> Use semicolon in inlined perf code

- lib/pageBuilderUtils.js
This reverts commit 343e55e9c56f7add234e0d88f7fcebd12b46ef2d, an attempt to fix [bug 1468271](https://bugzilla.mozilla.org/show_bug.cgi?id=1468271).
The problem is not some esoteric JavaScript optimization bug. Go back to the default minimization algorithm.
The problem is that the message handler in the main window is initialized after the message to set a mark for `interactive-editor-loading` (so the mark is not created), but before the message to set a measure starting on that mark (so there is an error raised). The fix will need to be on the Kuma side.
> Revert "Use semicolon in inlined perf code"

- js/editor-libs/analytics.js
- js/editor-libs/events.js
- js/editor-libs/mce-utils.js
- js/editor-libs/perf.js
Add a global configuration ``ieConfig``, with a single member ``origin`` for the target origin for ``postMessage`` calls. Allow overriding the origin with ``?origin=https://example.com``.
Fixes #257.
> Add window.ieConfig.origin for the target origin

- Jenkinsfile
- bin/irc-notify.sh
This PR allows this Jenkinsfile to run on both the new IT-owned Jenkins service as well as the existing MozMEAO-owned Jenkins service.
- Changes the name of the S3 bucket (to which the build artifacts will be sync'ed) depending upon the Jenkins service.
- Change the `bin/irc-notify.sh` script to use `RUN_DISPLAY_URL` instead of the fixed `BLUE_BUILD_URL`
I also took the liberty of making the indentation consistent (4 spaces). For easier review, you may want to check the `Hide whitespace changes` checkbox under the `Diff settings` button.
These changes have been successfully tested on both the new IT-owned Jenkins service and the existing MozMEAO-owned Jenkins service.
> bug 1483072: handle new jenkins/aws services

- Jenkinsfile
- bin/s3-sync.sh
The MozMEAO-owned Jenkins service uses locally-installed AWS credentials within the `mdninteractive` profile in order to perform its `aws s3 sync` command, but the new IT-owned Jenkins service has moved to the AWS-recommended approach of associating IAM roles with EC2 instances (see https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html). This PR allows us to satisfy both approaches during this interim period until we make the cutover to the IT-owned services.
This has been successfully tested for both the new IT-owned and MozMEAO-owned Jenkins services.
> bug 1483072: make awscli profile optional

- live-examples/html-examples/image-and-multimedia/audio.html
The ``http://`` URL results in a mixed content warning when [embedded on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio).
Both links work:
* https://soundbible.com/mp3/Tyrannosaurus%20Rex%20Roar-SoundBible.com-807702404.mp3
* http://soundbible.com/mp3/Tyrannosaurus%20Rex%20Roar-SoundBible.com-807702404.mp3
> Switch to https source for HTML audio example

- live-examples/js-examples/promise/promise-constructor.html
Showing that a promise evaluates to the string descriptor: `[object Promise]` is not the **most helpful** thing to include in the _first_ example.
Let me know if I need to revise, thanks for any feedback! 💯
> Added more helpful technique for accessing promise

- live-examples/html-examples/input/password.html
[HTML element names are case sensitive](https://www.w3.org/TR/1999/REC-html401-19991224/struct/global.html#adef-id)
> Fix incorrect label selector in password example

- live-examples/html-examples/embedded-content/picture.html
As discussed in #1085.  
Updated the media attribute in the `<picture>` example to make it work better on smaller screens.  🙂
> Updating picture example to work better on small screens

- js/editor-libs/css-editor-utils.js
https://github.com/mdn/interactive-examples/issues/1148
The first item still auto selects/inits so it's only one click to put the cursor in not two.
> Remove auto focus

- css/editor-libs/codemirror-override.css
Update colour contrast of commented code
The current contrast is 3.49:1, which is below the minimum 4.5 ratio needed to meet the WCAG AA guidelines. The proposed change increases the contrast to 4.52:1
Example of how new contract looks
also see bug https://bugzilla.mozilla.org/show_bug.cgi?id=948422
> Bugfix 948422: increase colour contract of comments in code examples

- live-examples/html-examples/content-sectioning/css/h1-h6.css
- live-examples/html-examples/content-sectioning/h1-h6.html
- live-examples/html-examples/content-sectioning/meta.json
This adds the missing h1-h6 interactive example. @wbamberg r?
> Adds h1-h6 example

- live-examples/js-examples/string/string-normalize.html
The error in the ternary operator.
> Fix bug in String.normalize live example

- CONTRIBUTING-HTML.md
- live-examples/html-examples/embedded-content/picture.html
- live-examples/html-examples/image-and-multimedia/img.html
- live-examples/html-examples/text-content/figcaption.html
- live-examples/html-examples/text-content/main.html
Fixed #1192 by changing media `src` to flat `/examples` folder.
> Issue#1192 links to media files broken

- live-examples/js-examples/object/object-entries.html
JS example for ```Object.entries( )```  contains wrong output value , which is being corrected
>  Js example output value changed 

- live-examples/css-examples/positioned-layout/position.css
- live-examples/css-examples/positioned-layout/position.html
This fixes #1115 by building on top of PR #1121 (using prefixed `-webkit-sticky` and making the boxes `display: block`).
The remaining issue was the fixed height of the inner container `.example-element-container` which Safari seems to use for calculating how long a sticky element is allowed to scroll (even if it is scrollable itself). Removing any height constraints on that `div` and instead making the outer section `overflow: auto` solved the problem (tested in Safari 12.0, FF, and Chrome).
I also recreated the blue boxes/placeholder behavior from before, removed the animation (was quite confusing for me, because you cannot animate `position` changes), and fixed the code formatting a bit.
> Fix #1115: position: sticky not working in Safari

- live-examples/css-examples/logical-properties/meta.json
https://github.com/mdn/interactive-examples/pull/1209 updated the names of some of the CSS logical properties but didn't update meta.json, which causes `npm run build` and `npm run start` to fail.
This hopefully fixes things.
> Fix logical properties

- live-examples/css-examples/logical-properties/meta.json
- live-examples/html-examples/interactive-elements/meta.json
Part of #1138: this part addressed the examples in the "interactive elements" category, following the notes in column C of https://docs.google.com/spreadsheets/d/1EC23mRNF7i-Bd29A4wEcFV_iiThL1P-NBtH4lzme8eM/edit#gid=0.
Note that this also include #1217, since I needed that to test the examples.
Tiny changes - there are only 2 examples and they are nice and simple already. I've just set the editor to "shorter" for them both.
> Update interactive elements examples

- live-examples/html-examples/table-content/caption.html
- live-examples/html-examples/table-content/col.html
- live-examples/html-examples/table-content/colgroup.html
- live-examples/html-examples/table-content/css/caption.css
- live-examples/html-examples/table-content/meta.json
- live-examples/html-examples/table-content/table.html
- live-examples/html-examples/table-content/tbody.html
- live-examples/html-examples/table-content/tfoot.html
- live-examples/html-examples/table-content/thead.html
Part of #1138: this part addressed the examples in the "table content" category, following the notes in column C of https://docs.google.com/spreadsheets/d/1EC23mRNF7i-Bd29A4wEcFV_iiThL1P-NBtH4lzme8eM/edit#gid=0.
The problem with this category is, the examples look fine but it's not really possible to show these elements outside the context of a table. This has a couple of consequences:
* it's hard to see the target of an example right away, because there's so much markup
* it's very hard to write markup for a table that fits into 14 lines, which is all we get for the "standard" height editor.
I don't like using the "taller" editor (23 lines) but I don't really see an alternative here.
So what I've done is:
* trimmed the examples to fit inside 23 lines, and to simplify them as much as I …
> Update table content examples

- live-examples/css-examples/logical-properties/meta.json
- live-examples/html-examples/inline-text-semantics/a.html
- live-examples/html-examples/inline-text-semantics/b.html
- live-examples/html-examples/inline-text-semantics/css/a.css
- live-examples/html-examples/inline-text-semantics/css/kbd.css
- live-examples/html-examples/inline-text-semantics/css/q.css
- live-examples/html-examples/inline-text-semantics/css/wbr.css
- live-examples/html-examples/inline-text-semantics/dfn.html
- live-examples/html-examples/inline-text-semantics/em.html
- live-examples/html-examples/inline-text-semantics/kbd.html
- live-examples/html-examples/inline-text-semantics/mark.html
- live-examples/html-examples/inline-text-semantics/meta.json
- live-examples/html-examples/inline-text-semantics/q.html
- live-examples/html-examples/inline-text-semantics/s.html
- live-examples/html-examples/inline-text-semantics/samp.html
- live-examples/html-examples/inline-text-semantics/small.html
- live-examples/html-examples/inline-text-semantics/span.html
- live-examples/html-examples/inline-text-semantics/sup.html
- live-examples/html-examples/inline-text-semantics/time.html
Part of #1138: this part addressed the examples in the "inline text semantics" category, following the notes in column C of https://docs.google.com/spreadsheets/d/1EC23mRNF7i-Bd29A4wEcFV_iiThL1P-NBtH4lzme8eM/edit#gid=0.
Note that this also include https://github.com/mdn/interactive-examples/pull/1217, since I needed that to test the examples.
Mostly these are quite small updates: simplifying the markup, changing the formatting for readability. I've also made most of them use the shorter editor since they tend to be very short examples.
> Update inline text semantics examples

- bin/build.sh
This PR resolves #1211 such that hopefully its root cause never happens again:
* remove the `node_modules` directory prior to calling `npm install` in order to prevent install failures due to conflicts between the contents of the `node_modules` directory leftover from the previous install and the current install
* `bin/build.sh` failures are no longer silent
This has been tested on Jenkins using a special test branch (`ryan-test`), both for the case of a successful build as well as for the case of a build failure.
> fix issues with the Jenkins build step

- live-examples/css-examples/grid/grid-template-areas.html
Clarifies the relationship between the divs in the rendered HTML and the the grid-area names in the grid-template-areas strings. For someone unfamiliar with the concepts already, the relationship between "One" "Two" and "Three" in the rendered HTML and "a" "b" and "c"  in the demo code can be confusing.
> Added grid-area label indicators to div content

- live-examples/css-examples/positioned-layout/position.html
Right now, the `position:sticky` demo CSS lists the prefixed value after the standard value.
Best practice is to use the opposite ordering -- putting the standard value last -- which ensures that it "wins" in cases where the browser supports both prefixed & unprefixed keywords and has quirky legacy behavior for the prefixed value.
> Put prefixed sticky value before standard value

- live-examples/js-examples/math/math-round.html
It confusing that there are three arguments to the first console.log also since the NodeSchool.io has a chapter about rounding numbers.
> Make the first Math.round example simpler

- live-examples/js-examples/intl/intl-relativetimeformat.html
- live-examples/js-examples/intl/meta.json
Adding RelativeDateFormat example , according to  https://github.com/tc39/proposal-intl-relative-time
> Adding  Intl.RelativeDateFormat example

- live-examples/js-examples/expressions/expressions-deleteoperator.html
Generic the code by replacing the human names with `foo-bar` convention instead
> Use foo-bar convention

- live-examples/css-examples/images/function-conic-gradient.html
- live-examples/css-examples/images/meta.json
added file for https://developer.mozilla.org/en-US/docs/Web/CSS/conic-gradient
> added conic gradient examples

- live-examples/css-examples/scrollbars/meta.json
- live-examples/css-examples/scrollbars/scrollbar-color.html
- live-examples/css-examples/scrollbars/scrollbar-common.css
- live-examples/css-examples/scrollbars/scrollbar-width.html
Fixes #1267 
- On Firefox 65 (beta) on MacOS (10.12 Sierra) and also on Windows 10 (1809), `scrollbar-color: dark` and `scrollbar-color: light` seems not to have any effect
- On Firefox 65 (beta) on MacOS (10.12 Sierra) and also on Windows 10 (1809), `scrollbar-color: <length>` seems not to have any effect
> Add CSS Examples for scrollbar-color and scrollbar-width

- live-examples/html-examples/forms/progress.html
Hi mdn 👋 !!
I've contributed in the past to the main docs but never to the coding examples, hope it's ok 😄 
This PR:
- remove the invalid attribute name from the progress element example
- formats the progress element file with prettier 
The main reason for removing this is: in my personal opinion every snippet / code example should be able to be dropped in file and should just work out of the box, in this particular case, working in a TypeScript project, the `ts-server` was complaining about the name attribute not be in the `HTMLProgressElement` interface.
After cheking this [https://developer.mozilla.org/en-US/docs/Web/API/HTMLProgressElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLProgressElement) the `ts-server` was right to complaing about the name attribure so I've …
> chore: remove invalid attribute in progress example

- live-examples/css-examples/scroll-snap/meta.json
- live-examples/css-examples/scroll-snap/scroll-margin-block-end.html
- live-examples/css-examples/scroll-snap/scroll-margin-block-start.html
- live-examples/css-examples/scroll-snap/scroll-margin-block.html
- live-examples/css-examples/scroll-snap/scroll-margin-bottom.css
- live-examples/css-examples/scroll-snap/scroll-margin-bottom.html
- live-examples/css-examples/scroll-snap/scroll-margin-inline-end.html
- live-examples/css-examples/scroll-snap/scroll-margin-inline-start.html
- live-examples/css-examples/scroll-snap/scroll-margin-left.html
- live-examples/css-examples/scroll-snap/scroll-margin-right.css
- live-examples/css-examples/scroll-snap/scroll-margin-right.html
- live-examples/css-examples/scroll-snap/scroll-margin-top.css
- live-examples/css-examples/scroll-snap/scroll-margin-top.html
- live-examples/css-examples/scroll-snap/scroll-margin.css
- live-examples/css-examples/scroll-snap/scroll-margin.html
- live-examples/css-examples/scroll-snap/scroll-padding-block-end.html
- live-examples/css-examples/scroll-snap/scroll-padding-block-start.html
- live-examples/css-examples/scroll-snap/scroll-padding-block.html
- live-examples/css-examples/scroll-snap/scroll-padding-bottom.css
- live-examples/css-examples/scroll-snap/scroll-padding-bottom.html
- live-examples/css-examples/scroll-snap/scroll-padding-inline-end.html
- live-examples/css-examples/scroll-snap/scroll-padding-inline-start.html
- live-examples/css-examples/scroll-snap/scroll-padding-inline.html
- live-examples/css-examples/scroll-snap/scroll-padding-left.html
- live-examples/css-examples/scroll-snap/scroll-padding-right.css
- live-examples/css-examples/scroll-snap/scroll-padding-right.html
- live-examples/css-examples/scroll-snap/scroll-padding-top.css
- live-examples/css-examples/scroll-snap/scroll-padding-top.html
- live-examples/css-examples/scroll-snap/scroll-padding.css
- live-examples/css-examples/scroll-snap/scroll-padding.html
This is a new PR to try and fix the unresolvable mess I created in my last one!
Old PR (which I will close) https://github.com/mdn/interactive-examples/pull/1260
I have added some text to each example which I help demonstrates what people are supposed to do.
I have removed `scroll-snap-align` as that shouldn't be in there until we decide what to do about this issue: https://github.com/mdn/interactive-examples/issues/1263
> New PR for scroll snap examples

- live-examples/css-examples/text/overflow-wrap.css
- live-examples/css-examples/text/overflow-wrap.html
added 'anywhere' value to bcd for overflow-wrap property
based on https://bugzilla.mozilla.org/show_bug.cgi?id=1505786 (FF 65 supports 'anywhere') 
spec: https://drafts.csswg.org/css-text-3/#propdef-overflow-wrap
> added anywhere value to overflow-wrap property

- live-examples/css-examples/text/text-transform.html
added kana example and full-size-kana value. Works in FF only.
https://bugzilla.mozilla.org/show_bug.cgi?id=1498148
https://drafts.csswg.org/css-text-3/#propdef-text-transform
https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform
> text-transform: full-size-kana value

- live-examples/js-examples/intl/intl-relativetimeformat-prototype-format.html
- live-examples/js-examples/intl/intl-relativetimeformat-prototype-formattoparts.html
- live-examples/js-examples/intl/intl-relativetimeformat-prototype-resolvedoptions.html
- live-examples/js-examples/intl/intl-relativetimeformat-supportedlocalesof.html
- live-examples/js-examples/intl/meta.json
Examples for
[RelativeTimeFormat.format](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat/format)
[RelativeTimeFormat.formatToParts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat/formatToParts)
[RelativeTimeFormat.resolvedOptions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat/resolvedOptions)
[RelativeTimeFormat.supportedLocalesOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat/supportedLocalesOf)
Remaining work to fix https://github.com/tc39/proposal-intl-relative-time/issues/102
cc @romulocintra 
This can be tested in the current Chrome release (71) or in the upcoming Firefox 65 …
> Add more Intl.RelativeTimeFormat examples

- live-examples/css-examples/text/overflow-wrap.css
- live-examples/css-examples/text/overflow-wrap.html
Reverts mdn/interactive-examples#1284
Nesting `overflow-wrap: anywhere` in `flex` element is unproperly. For better understand this rule see [this example](https://jsfiddle.net/ofgd83um/80/)
> Revert "added anywhere value to overflow-wrap property"

- live-examples/js-examples/string/string-replace.html
Otherwise, it's easy to miss this use case. Also, shows the single operation limit in contrast to using regex.
> Add example of string replace without regex

- live-examples/css-examples/text/overflow-wrap.css
- live-examples/css-examples/text/overflow-wrap.html
Finally found an example where anywhere is different from break-word. Squeee! 
for ticket #937
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap
> overflow-wrap: anywhere

- live-examples/js-examples/regexp/meta.json
- live-examples/js-examples/regexp/regexp-prototype-@@matchall.html
- live-examples/js-examples/string/meta.json
- live-examples/js-examples/string/string-matchall.html
- live-examples/js-examples/symbol/meta.json
- live-examples/js-examples/symbol/symbol-matchall.html
Examples for:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/matchAll
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/@@matchAll
This will work in Chrome 73 and Firefox 67 (or the nightly versions of these browsers).
> Add examples for matchAll

- live-examples/js-examples/object/object-entries.html
This PR fixes the example for [`Object.entries`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries), since both https://github.com/mdn/interactive-examples/pull/1238 and https://github.com/mdn/interactive-examples/pull/1303 seem to have stalled.
It's just a lightly cleaned-up version of https://github.com/mdn/interactive-examples/pull/1238#issuecomment-440647014.
> Fix Object.entries example

- live-examples/css-examples/scroll-snap/meta.json
- live-examples/css-examples/scroll-snap/scroll-margin-inline.html
I failed to create an example for the two value shorthand scroll-margin-inline. This adds that example.
> Adding missing example

- live-examples/js-examples/dataview/dataview-getbigint64.html
- live-examples/js-examples/dataview/dataview-getbiguint64.html
- live-examples/js-examples/dataview/dataview-setbigint64.html
- live-examples/js-examples/dataview/dataview-setbiguint64.html
- live-examples/js-examples/dataview/meta.json
Examples for these pages:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/getBigInt64
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/getBigUint64
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setBigInt64
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setBigUint64
These example are very trivial and maybe not very useful, vut so are the other dataview getter/setter examples. Let me know if you have ideas and want me to try harder.
Looks better with https://github.com/mdn/bob/pull/254 which I spent more time on than the examples itself.
> Add samples for BigInt typed array API

- live-examples/html-examples/input/css/single-input.css
- live-examples/html-examples/input/tel.html
- live-examples/html-examples/input/time.html
In the HTML `<input>` examples, replaces the `<span class="note">` elements with “more semantic” `<small>` elements, where the note indicates a [small print](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/small) formatting guideline for users. Also deletes the unused `.note` CSS class for those examples.
I’ve checked through all the `/live-examples/html-examples/input/` HTML pages and ensured that `.note` wasn’t used before deleting it. The only pages that used it were `tel.html` and `time.html`, which have been updated with `<small>`.
> replace `span.note` with `small`

- live-examples/js-examples/bigint/bigint-asintn.html
- live-examples/js-examples/bigint/bigint-asuintn.html
- live-examples/js-examples/bigint/bigint-tolocalestring.html
- live-examples/js-examples/bigint/bigint-tostring.html
- live-examples/js-examples/bigint/bigint-valueof.html
- live-examples/js-examples/bigint/meta.json
Examples for:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt/asIntN
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt/asUintN
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt/toLocaleString (only works in Chrome 76 for now, soon in Nightly)
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt/toString
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt/valueOf
> Add examples for BigInt API

- live-examples/css-examples/motion-path/meta.json
- live-examples/css-examples/motion-path/offset-distance.css
- live-examples/css-examples/motion-path/offset-distance.html
- live-examples/css-examples/motion-path/offset-path.css
- live-examples/css-examples/motion-path/offset-path.html
- live-examples/css-examples/motion-path/offset-playback.js
- live-examples/css-examples/motion-path/offset-rotate.css
- live-examples/css-examples/motion-path/offset-rotate.html
This PR adds demos for `offset-path` (only showing the `path()` syntax for now since that is the only supported function in browsers currently (Blink and Firefox Nightly)), `offset-rotate`, and `offset-distance`.
The offset properties are interesting that by themselves they don't really show much. For example, defining an `offset-path` but nothing else shows very little, as it simply defines a path that it will follow when adjusted by the other `offset` properties. Similarly `offset-distance` and `offset-rotate` are meaningless without an `offset-path` defined.
For `offset-distance` and `offset-rotate`, I added a background image that represents a common `offset-path` that the examples all use. I'm concerned that could be confusing since the path is technically invisible, but it felt more …
> Offset Path (CSS Motion Path) properties

- live-examples/js-examples/globalprops/globalprops-encodeuri.html
I was reading the documentation for encodeURI() and noticed that the example had an extra quotation mark in the comment. This edit fixes it.
> encodeURI() Example Removed Extra Quotation Mark

- live-examples/js-examples/expressions/expressions-optionalchainingoperator.html
- live-examples/js-examples/expressions/meta.json
This adds a basic interactive example for a new (stage 3) operator
- Spec: https://github.com/tc39/proposal-optional-chaining/
- Target page on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
- Bug for implementation with DDN: https://bugzilla.mozilla.org/show_bug.cgi?id=1566143
> Adding optional chaining operator example

- live-examples/html-examples/forms/meter.html
The `<meter>` element is an output, not an input type element that can POST to a form. The `[name]` attribute is not valid on this element.
> Fix #1351 - <meter> example has name attribute, but name attribute not listed in docs

- live-examples/html-examples/input/time.html
Fixes issue where the `[min]` attribute of the `<input type="time">` element was not in proper time value format.
> Fix #1240 - [HTML Examples] input ~ <input type="time">

- JS-Example-Style-Guide.md
Referencing #1404, this should resolve the discrepancy of when to use ES5/ES6 by updating the style guide to reflect that MDN guidelines specify to use ES6 for examples when possible.
> Fix #1409 - Make interactive examples style guide consistent with MDN examples style guide

- live-examples/html-examples/image-and-multimedia/img.html
The example used '/>' which was used in XHTML.
Now it uses proper HTML5. i.e. '>'
> Updated img example to HTML5

- live-examples/css-examples/basic-box-model/meta.json
- live-examples/css-examples/basic-box-model/overflow-block.html
- live-examples/css-examples/basic-box-model/overflow-inline.html
These properties are shipping in Firefox 69, and the examples are essentially a copy of `overflow-x` and `overflow-y` as the flow relative properties map to these.
https://bugzilla.mozilla.org/show_bug.cgi?id=1470695
> Adding examples overflow-block and overflow-inline

- .gitignore
- bin/build.sh
Update build script to have docker pass the HOME environment variable.
This ensures all the directories node creates has the right permissions
which will allow the jenkins workspace cleaner to work properly.
> Build script now will now set HOME variable to /mdn

- live-examples/js-examples/statement/statement-throw.html
Throw's generating error message so it should go to console.error() not console.log().
> More up-to-date method on console

- live-examples/js-examples/promise/promise-reject.html
Current practice is to emit errors through console.error() not console.log()
> console method changed to console.error()

- package-lock.json
- package.json
`npm install` is giving us lots of security warnings. This PR is the result of running `npm audit fix`. There are some warnings still, but I thought we could apply these now and then handle the rest in a separate PR.
> Apply npm audit fix

- live-examples/js-examples/statement/statement-forof.html
I don't think generators should be the intro-example to for-of iterating. This changes it to basically the same as the for-each example.
Very much inspired by @ryanflorence's tweet: https://twitter.com/ryanflorence/status/1178450087531311104?s=20
> Change for-of example to something simpler

- package-lock.json
- package.json
The description for the select contains the following text: 
> The above example shows typical usage. It is given an id attribute to enable it to be associated with a for accessibility purposes, as well as a name attribute to represent the name of the associated data point submitted to the server.  
The name attribute mentioned in the text is missing in the example. This adds the name attribute.
> Add name attribute to select example

- live-examples/js-examples/statement/statement-forin.html
This PR modifies current example of for..in statement, which I've found to be slightly misleading because of those string concatenation. I would like to propose the following trivial example, which is more transparent and readable at the first glance, same as [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of)'s example.
> Edit for-in statement example

- live-examples/js-examples/globalprops/globalprops-decodeuri.html
- live-examples/js-examples/globalprops/globalprops-encodeuri.html
- live-examples/js-examples/globalprops/globalprops-infinity.html
- live-examples/js-examples/globalprops/globalprops-null.html
- live-examples/js-examples/globalprops/globalprops-parseint.html
- live-examples/js-examples/globalprops/globalprops-undefined.html
This PR aims to replace `var` keyword with `let` and `const` in live examples for the globalprops
> Use ES6 variable declaration in globalprops live examples

- live-examples/css-examples/animation/animation.html
The animation's \<keyframes-name\> should be the last value provided, not the first[1] (though it looks like it might still work either way in many cases).
The position is only incorrect in this interactive code example; the wiki page itself is correct. 
1. https://www.w3.org/TR/css-animations-1/#animation
> corrects usage of <keyframes-name> in `animation` shorthand

- live-examples/js-examples/expressions/expressions-nullishcoalescingoperator.html
- live-examples/js-examples/expressions/meta.json
As [nullish coalescing operator](https://github.com/tc39/proposal-nullish-coalescing) is now a TC39 proposal of Stage 3 and has been implemented in [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1566141) and in [Safari](https://webkit.org/blog/9497/release-notes-for-safari-technology-preview-89/), I wrote the [corresponding page](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) and provide the corresponding interactive example.
The example worked as intended on my machine using the last Firefox Nightly.
> Adding interactive examples for nullish coalescing operator

- live-examples/js-examples/expressions/expressions-propertyaccessors.html
- live-examples/js-examples/intl/intl-collator-prototype-resolvedoptions.html
- live-examples/js-examples/intl/intl-collator-supportedlocalesof.html
- live-examples/js-examples/intl/intl-datetimeformat-prototype-format.html
- live-examples/js-examples/intl/intl-datetimeformat-prototype-formatrange.html
- live-examples/js-examples/intl/intl-datetimeformat-prototype-resolvedoptions.html
- live-examples/js-examples/intl/intl-datetimeformat-supportedlocalesof.html
- live-examples/js-examples/intl/intl-datetimeformat.html
- live-examples/js-examples/intl/intl-locale-prototype-maximize.html
- live-examples/js-examples/intl/intl-locale-prototype-minimize.html
- live-examples/js-examples/intl/intl-locale-prototype-tostring.html
- live-examples/js-examples/intl/intl-numberformat-prototype-format.html
- live-examples/js-examples/intl/intl-numberformat-prototype-resolvedoptions.html
- live-examples/js-examples/intl/intl-numberformat-supportedlocalesof.html
- live-examples/js-examples/intl/intl-numberformat.html
- live-examples/js-examples/intl/intl-relativetimeformat-prototype-format.html
- live-examples/js-examples/intl/intl-relativetimeformat-prototype-formattoparts.html
- live-examples/js-examples/intl/intl-relativetimeformat-prototype-resolvedoptions.html
- live-examples/js-examples/intl/intl-relativetimeformat-supportedlocalesof.html
- live-examples/js-examples/intl/intl-relativetimeformat.html
With this PR I would like to standardize the `Intl` related examples by
- using consequently es6 variable declarations
- using consistent styleguide
- adjusting the expected output
> Use ES6 variable declarations in the `Intl` examples

- live-examples/js-examples/array/array-concat.html
While it may be apparent in the current example. I feel like making a new variable very explicitly shows that `concat` returns a new array in the code example which is the first place I personally look
> Explicitly call out return value in code example

- live-examples/js-examples/regexp/meta.json
- live-examples/js-examples/regexp/regexp-assertions.html
As part of https://github.com/mdn/sprints/issues/1721, I'll be adding both inline / interactive examples.
A few notes about this one:
* Although lookbehind assertions are stage 4, they don't currently work in Fx and make the example slightly longer than 12 lines. I think it is better to include at least one of the "lookbehind" pattern but feel free to voice your objection
* This target a feature of the language but not a property or a method.
> Adding regexp assertions

- live-examples/js-examples/regexp/meta.json
- live-examples/js-examples/regexp/regexp-unicode-property-escapes.html
As part of https://github.com/mdn/sprints/issues/1721 and in order to add interactive examples on https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes, I propose this PR.
As this feature is not supported by Fx and that I don't have a macOS/iOS device, I was only able to test this on Chrome / Chromium.
> Interactive examples for RegExp Unicode Property Escapes

- live-examples/html-examples/inline-text-semantics/cite.html
The `<cite>` element already makes the text italicized by default. From the [MDN `<cite>` reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/cite):
> Typically, browsers style the contents of a <cite> element in italics by default. 
Removing `<i>` for simplicity.
> Improv cite example

- live-examples/js-examples/string/string-normalize.html
As part of https://github.com/mdn/sprints/issues/2594 I decided that the interactive example for [`normalize()`](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize ) is not very readable: these long lines assembling complex strings are hard to follow.
So this PR rewrites it. It only covers "NFD" and "NFC", but is already as long as I'd like an example to be.
> Replace example for string.normalize()

- live-examples/js-examples/date/date-tolocaledatestring.html
This is a common use case, but doesn't have an example currently.
> Added example for toLocaleDateString(undefined, options)

- live-examples/html-examples/input/range.html
In the first example on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range the label is not linked to the input, so clicking on it wont transfer the focus to the range slider.
> Make volume range controller accessible with label

- CONTRIBUTING-JavaScript.md
- CONTRIBUTING.md
This PR updates our contribution docs now we:
* provide JS examples in .js files, rather than .html files
* calculate the JS editor height automatically
@ikarasz , please let me know if this looks good to you.
> Update contribution docs now we supply JS examples in .js files

- live-examples/js-examples/array/array-iterator.js
- live-examples/js-examples/array/meta.json
Simple PR for adding a live sample for the `Array[Symbol.iterator]` method, based on the example given on [Array.values](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/values) method.
> Add live example for Array iterator

- JS-Example-Style-Guide.md
- package.json
I thought it would be helpful to expose ESLint's `--fix` option, so contributors can easily fix up code with lint errors.
> Add lint-fix command

- live-examples/js-examples/string/meta.json
- live-examples/js-examples/string/string-replaceall.js
For https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll
Basically a copy of https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace which is a bit lame, but I guess it makes sense to also show this with string argument and with a regex argument.
Happy to hear better proposals
> Add example for String replaceAll

- live-examples/css-examples/transforms/rotate3d.css
The perspective is **rotating with the whole block** in the live example.
I just moved the appropriate property to container, so perspective origin is not moving anymore. You can see the difference below.
> Fix perspective in rotate3d() example 

- live-examples/js-examples/expressions/expressions-yield.js
Docs are most effective when few ideas are required to comprehend the definition.
It's easier to understand what a keyword does when it is isolated.  Let's move the "++" to a different expression. It's not fundamental to the definition of yield. 
We want to be clear that we yield the value and then increment. In general, the distinction between ++var and var++ can be difficult for early developers. We should minimize the "confusion surface area" (borrowing a term from security) and just be explicit.  This makes it easier for any reader to understand what yield means.
aka
"Don't use big words in your dictionary definitions"
> Update expression yield live example for clarity.

- .eslintrc.js
- live-examples/js-examples/map/map-prototype-@@iterator.js
- live-examples/js-examples/proxyhandler/proxyhandler-ownkeys.js
- live-examples/js-examples/regexp/regexp-prototype-@@matchall.js
- live-examples/js-examples/set/set-prototype-add.js
- live-examples/js-examples/set/set-prototype-entries.js
- live-examples/js-examples/string/string-iterator.js
- live-examples/js-examples/string/string-matchall.js
- live-examples/js-examples/symbol/symbol-matchall.js
In reviewing https://github.com/mdn/interactive-examples/pull/1621 I complained about some `let` declarations that could (and therefore should) be `const`: since ESLint can enforce this for us I thought it would be worth doing.
This PR adds [`prefer-const`](https://eslint.org/docs/rules/prefer-const) to our default config, and various automatic fixes that look reasonable.
I've also relaxed `prefer-const` for three examples:
* https://github.com/mdn/interactive-examples/blob/master/live-examples/js-examples/statement/statement-block.js, where using `let` seems more plausible
* https://github.com/mdn/interactive-examples/blob/master/live-examples/js-examples/statement/statement-let.js, where using `let` is obviously needed
* https://github.com/mdn/interactive-examples/blob/master/live-exampl …
> Add prefer-const to ESLint config

- live-examples/html-examples/embedded-content/picture.html
The alt attribute is required in HTML and must always be included for accessibility. Since we’re switching between two complete different images here, and it's just a demo, we can keep the alt attribute empty.
> Add alt attribute on <picture> example

- live-examples/css-examples/fonts/font-optical-sizing.css
- live-examples/css-examples/fonts/font-optical-sizing.html
I was looking at the example for https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/font-optical-sizing, and thought it would be better to include both larger and smaller font sizes, so we could see the effect on both. Especially I thought it would be good to show improved legibility at smaller sizes.
> Improve font-optical-sizing example

- live-examples/html-examples/image-and-multimedia/track.html
The `mp4` for the track.html example is linked incorrectly. Video
files are all located inside the `media/cc0-videos` folder
fix #1683
> (fix) media file for track.html missing

- live-examples/js-examples/math/math-random.js
The correction is regarding the usage of word here.
Since Math.random() always returns a value 0 <= x < 1, using the word 'between' in  "expected output: a number between 0 and 1" falsely indicates that the function Math.random() does not ever return 0.
> Fix Grammar Error in a comment

- CONTRIBUTING-JavaScript.md
It wasn't clear to me until I ran the example that this property reflects a file that is autogenerated.
> JavaScript example metdata fileName is for autogenerated HTML

- live-examples/js-examples/intl/intl-prototype-@@tostringtag.js
- live-examples/js-examples/intl/meta.json
This adds trivial example for `Intl[Symbol.toStringTag]`  following its addtition in https://bugzilla.mozilla.org/show_bug.cgi?id=1670053
This is to populate https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/@@toStringTag
Tested on a codepen. Seems to work OK. But I am not great a JavaScript, so appreciate your review!
> Add example for Intl.toString

- live-examples/html-examples/text-content/blockquote.html
The [spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element) for `<blockquote>` states:
> Attribution for the quotation, if any, must be placed outside the blockquote element.
I changed the semantics to one of the examples in the spec.
Fixes mdn/sprints#2705
> move attribution out of <blockquote>

- live-examples/html-examples/content-sectioning/nav.html
The href values of the breadcrumbs cause a 404 error in the example when clicked. This PR changes them to "#".
@chrisdavidmills: Fixes mdn/sprints#3454
> change hrefs to '#' in nav example

- live-examples/css-examples/transforms/meta.json
- live-examples/css-examples/transforms/perspective-origin.css
Reported in https://github.com/mdn/sprints/issues/3922 the `perspective-origin` demo wasn't working.
It was referencing the CSS file for `perspective` which meant it didn't have the `perspective` property set and therefore `perspective-origin` quite reasonably wasn't doing anything. I have set it to ref a separate CSS file which adds back the property.
> fixing perspective-origin

- live-examples/js-examples/intl/intl-datetimeformat.js
Previous example just shows default formatting based on locale, and locale with language fallback. This extends the example just a little to show how the date can be formatted using style and custom options.
> Update Intl.DateTimeFormat to show options in constructor

- live-examples/html-examples/global-attributes/attribute-enterkeyhint.html
- live-examples/html-examples/global-attributes/css/attribute-enterkeyhint.css
- live-examples/html-examples/global-attributes/meta.json
Interactive example for https://github.com/mdn/content/pull/1106
It just shows how it works with an input element and contenteditable.
I managed to get it all running locally with Yari, so here's the rendering of that:
Not sure why the CSS file is needed but the other global attributes have that, too.
> Add enterkeyhint example

- live-examples/css-examples/values-and-units/type-basic-shape.html
Adding path() as a basic shape.
It is not supported in clip-path. (but it is supported in offset-path in FF63, with motion path in Chrome)
specs: 
Definition of path()
https://drafts.csswg.org/css-shapes-2/#supported-basic-shapes
to be added to basic shapes at:
https://www.w3.org/TR/css-shapes/#basic-shape-functions
as per bugzilla
https://bugzilla.mozilla.org/show_bug.cgi?id=1246764
> added path() example to basic shapes (CSS values)

- live-examples/js-examples/regexp/regexp-prototype-test.js
I'm still baffled that it worked with `const regex = Regex(...)` without the `new`.
> Add 'new' for constructor and remove repeated line

- live-examples/js-examples/intl/intl-collator.js
This modifies the Intl.Collator() example to show how you can use options, since these can radically affect behaviour.
Note that I could have extended the function to pass through the options as well, but decided not to - IMO better to show the actual call as a user will try it.
Appreciate this is arguable.
> Add options example to intl-collator

- live-examples/js-examples/typedarray/typedarray-of.js
`new Int16Array` creates an array of signed integers; so using “uint16” as the name of the variable it get assigned to is confusing — because the “u” part by convention is used for indicating *unsigned*.
Fixes https://github.com/mdn/content/issues/1283
> Change uint16→int16array in TypedArray.of example

- live-examples/js-examples/regexp/meta.json
- live-examples/js-examples/regexp/regexp-prototype-hasindices.js
This adds an interactive example for the [newly introduced `RegExp.prototype.hasIndices`](https://bugzilla.mozilla.org/show_bug.cgi?id=1519483) property.
This is in preparation of adding the related content.
Sebastian
> Added example for RegExp.prototype.hasIndices

- .eslintrc.js
- package.json
- yarn.lock
Changing the `no-invalid-regexp` rule to a warning (rather than a error), but only for `**/regexp/regexp-prototype-hasindices.js`. We can remove this change once `eslint` recognizes the `"d"` flag to the `RegExp` constructor.
This will get the builds passing again after they were broken by #1782.
> change no-invalid-regexp to warn for hasindices

- .eslintrc.js
- live-examples/css-examples/logical-properties/border-inline-color.html
- live-examples/css-examples/logical-properties/border-inline-style.html
- live-examples/css-examples/logical-properties/border-inline-width.html
- live-examples/css-examples/logical-properties/border-inline.html
- live-examples/css-examples/logical-properties/meta.json
- package.json
- yarn.lock
Fixes: #1638 
Adds the examples for `border-inline` and longhands.
> Adds the border-inline examples

- live-examples/css-examples/text-decoration/meta.json
- live-examples/css-examples/text-decoration/text-emphasis-color.css
- live-examples/css-examples/text-decoration/text-emphasis-color.html
- live-examples/css-examples/text-decoration/text-emphasis-position.css
- live-examples/css-examples/text-decoration/text-emphasis-position.html
- live-examples/css-examples/text-decoration/text-emphasis-style.html
Fixes #1644 
There were already examples for style and color, but they haven't been added to pages and needed the -webkit prefixed versions. So I have added that and also the text-emphasis-position example.
> text-emphasis examples

- live-examples/css-examples/text/tab-size.html
Firefox supports tabSize example
#1645
> Fix: tabSize example support 

- live-examples/css-examples/grid/grid-auto-rows.css
- live-examples/css-examples/grid/grid-auto-rows.html
Resolves #1801 @wbamberg 
> Yes the "missing" text was intentional as otherwise you can't see the difference (it's a bit tricky in such a small space). I think the solution of adding a smaller font size would work.
In this [comment](https://github.com/mdn/interactive-examples/pull/1801#issuecomment-830572374), @rachelandrew mentioned that adding a smaller font size for the last element would be a way to resolve this. I'm happy to push another commit and remove the text content if its more preferred without text to really highlight the different heights the last box will occupy.
> Add smaller font-size for last element in grid-auto-rows demo

- live-examples/html-examples/global-attributes/attribute-title.html
- live-examples/html-examples/global-attributes/css/attribute-title.css
Change the `title` attribute interactive example as the current example use case is problematic from an accessibility perspective and is not the best use case to use for the example.
fix #1822
/cc @ericwbailey
> fix: change title attribute example

- live-examples/html-examples/text-content/main.html
- live-examples/webapi-examples/document/queryselector/document-queryselector.html
Per the ARIA in HTML spec at https://w3c.github.io/html-aria/#el-main, the `main` element should have no role value; its implicit role is `main`, and at https://w3c.github.io/html-aria/#rules-wd, the spec says:
> It is NOT RECOMMENDED for authors to set the ARIA role and aria-\* attributes to values that match the implicit ARIA semantics defined in the table. Doing so is unnecessary and can potentially lead to unintended consequences.
Fixes https://github.com/mdn/content/issues/5461
> Drop role=main from <main> element

- live-examples/css-examples/flexbox/flex-basis.css
- live-examples/css-examples/flexbox/flex-basis.html
Fixes #1828 
The "side by side" layout doesn't change, but we could perform the same column layout shift like I proposed in #1825 and that could be one more commit added here before this PR is ready to merge.
> Add auto width to .example-container for flex-basis interactive demo

- live-examples/html-examples/input/email.html
While the example suggests that it checked for `globex.com` email addresses, the
pattern accepted any character instead of the dot before `com`. So it matched
for example `foo@globexZcom`.
While it's harmless in our setting, we want to alert users that they have to
escape dots in regular expressions if they intend to only match dots, we set a
good example and escape the dot before `com`.
> html/input: Escape dot in regular expression for email

- live-examples/html-examples/inline-text-semantics/cite.html
I don't think `<footer>` was meant to be used with non-sectioning content like this. The [page for `blockquote`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote) contains what I believe to be the correct markup,  [corroborated by the HTML living spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element).
(Update: the `<footer>` usage was previously recommended in the W3C HTML spec)
> Fixes markup for <cite> example

- live-examples/js-examples/typedarray/typedarray-from.js
The extra `new` step isn't necessary before using `Int16Array.from`, is it?
> Remove extra "new" instantiation from TypedArray.from() live demo

- live-examples/css-examples/text/text-transform.html
This example will benefit significantly by adding a word in ALL CAPS so developers can see how an all caps word is affected.
Fortunately, the first word of the quote from Dickens affords this opportunity perfectly.  According to [GoodReads](https://www.goodreads.com/quotes/195229-london-michaelmas-term-lately-over-and-the-lord-chancellor-sitting), the word "London" should be in all caps, so this improvement is a win-win.
> Significantly improve by adding an ALL CAPS word

- live-examples/js-examples/map/map.js
- live-examples/js-examples/map/meta.json
I think it would be helpful to have an example showcasing a `Map`'s general functionality, so I created an interactive example doing exactly that.
I think it would be useful if we showed this interactive example at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map, since that page has no interactive examples at the time of this writing.
> add example showcasing basic map functionality

- live-examples/js-examples/intl/intl-pluralrules-supportedlocalesof.js
- live-examples/js-examples/intl/meta.json
Fixes #1652 
Assuming a runtime that supports English, Arabic (Oman), and German (Germany) but not Balinese in PluralRules.
> Add interactive example for Intl.PluralRules.supportedLocalesOf

- live-examples/js-examples/intl/intl-datetimeformat-prototype-formatrangetoparts.js
The expected output of the [Intl.DateTimeFormat.prototype.formatRangeToParts()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRangeToParts) example depends on the timezone in which you run the example. 
This just adds the clarification to the output: 
> expected output *(in GMT timezone)*:
This is part of https://github.com/mdn/content/issues/6710
> Add comment that results depend on timezone

- live-examples/css-examples/text/text-align.html
A small fix based on this content issue: https://github.com/mdn/content/issues/7295
> use start and end instead of left and right for the text-align property

- live-examples/js-examples/array/array-reduce.js
For consistency with https://github.com/mdn/content/commit/260094b changes (https://github.com/mdn/content/pull/7484), this change replaces the variable name `accumulator` with `previousValue` in the `live-examples/js-examples/array/array-reduce.js` live-example source.
Cc @hamishwillee
> “accumulator”→“previousValue” in array-reduce.js live example

- live-examples/js-examples/number/number-min-value.js
the eariler code,at line no.3 had a return of 'process as infinity' with a negative value attached to it, this is a false operation for MIN_VALUE, which represents the adjacent positive value to 0, and not the most negative number
> Updated code bug

- live-examples/css-examples/fonts/font-synthesis.css
- live-examples/css-examples/fonts/font-synthesis.html
Part of https://github.com/mdn/content/issues/8611
Adds `small-caps` to the `font-synthesis` example.
> Adds the small-caps keyword

- live-examples/css-examples/lists/counter-reset.css
https://github.com/mdn/content/issues/6277 (and the linked bugzilla issue) explain why the counter-reset example is confusing. I've updated it as suggested in the bugzilla bug.
Once this is merged and showing up I'll go add an explanation under the example.
> Change counter-reset example to use counters() not counter()

- live-examples/css-examples/basic-user-interface/accent-color.css
- live-examples/css-examples/basic-user-interface/accent-color.html
- live-examples/css-examples/basic-user-interface/meta.json
Added a live example of the `accent-color` property from https://drafts.csswg.org/css-ui-4/#widget-accent. To test you need Chrome 91+ with the `experimental-web-platform-features` flag enabled, or Firefox 90+ with the `layout.css.accent-color.enabled` flag enabled.
Shipping on by default in Chrome 93 and Firefox 92.
> Add live example for `accent-color` css property.

- CONTRIBUTING.md
Perfectly valid javascript can still fail to merge due to the linter - that will, for example, cause a fail based on snake rather than camel case for property names. This suggests running `yarn test` before submitting to CI. We might perhaps instead/as well point to linter rules, but this is easier. 
Note, this actually doesn't work well on Windows, which gives you lots of spurious line ending related errors.
> CONTRIBUTING - suggest running yarn test

- live-examples/html-examples/text-content/main.html
Per "Document conformance requirements for use of
ARIA attributes in HTML"
https://www.w3.org/TR/html-aria/#docconformance 
"explicitly assigning [the element’s implicit
role] in markup is NOT RECOMMENDED”.
> Removes redundant aria role attribute

- live-examples/js-examples/date/date-gettime.js
Fixes mdn/content#8831
(Note this really is the UTC time and not the GMT one, but it will add confusion to translate it (UTC and GMT are off by a few seconds)
> Fix moon landing date

- .eslintignore
- live-examples/js-examples/classes/classes-static-initialization.js
- live-examples/js-examples/classes/meta.json
This adds examples for class static initialization block, added in FF93 . This will appear in docs here: https://github.com/mdn/content/pull/9281
There is a lot that might be shown. This primarily just shows the syntax for declaring a block, and that it can access/declare a property using the `this`.
> Add class static initialization block example

- live-examples/js-examples/expressions/expressions-remainder.js
Also see mdn/content#10290
using 12%5 to explain how the remainder operator works to some of my coding students was confusing for them since the result of integer division 12 / 5 is also 2. I explained that 12 / 5 is 2 with a remainder of 2, so 12 % 2 === 2. Many of them mistakenly thought that that % was just an integer division.
I think using 13 in the example would reduce the confusion since the result of integer division 13 / 2 (2) is different from the remainder (3).
@wbamberg
> change examples for Remainder operator to use 13 instead of 12

- live-examples/html-examples/inline-text-semantics/css/a.css
In https://github.com/mdn/content/issues/10459 someone was confused that after removing all the content from the links the icons still showed up in the example. I agree that this is confusing and suggest we remove the `::before` style so we just show the default behavior.
> Remove styling for anchor example

- .eslintignore
- .eslintrc
- live-examples/js-examples/classes/classes-static-initialization.js
- live-examples/js-examples/classes/classes-static.js
Now we have ESLint 8 (thanks @schalkneethling ) we should be able to unpick some of the tweaks we had to make:
* undo changes to stop ESLint complaining about static classes, now it supports them (fixes https://github.com/mdn/interactive-examples/issues/1922)
* fix actual lint errors in those examples
* undo https://github.com/mdn/interactive-examples/pull/1798 now ESLint supports `hasIndices`
> Update ESLint config for version 8

- live-examples/html-examples/document-metadata/style.html
Fixes https://github.com/mdn/interactive-examples/issues/1957.
> Remove deprecated type attribute from style element example

- live-examples/css-examples/text/tab-size.html
Moves up the vendor prefix `-moz-tab-size` so that the main property gets applied if it is supported by the browser.
> 🔥 Retire firefox vendor prefix from example

- live-examples/js-examples/object/object-hasown.js
Looking at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn , I thought the example has some consistency and readability issues:
* no whitespace between parts of the example
* extra conditional instead of a more concise `console.log()` statement
* extra comments: it's a general policy for examples to "show, not tell". They appear in a documentation page that explains all about the feature in prose. It's better for the example just to be a usage example
* `expected output` should be on the next line and exactly match the expected output with nothing extra
* edge cases: this is arguable but: it's much better if the examples can fit inside 12 lines, so they get the medium-sized editor. It's only really desirable to have a bigger example if it's …
> Update hasOwn example for readability

- live-examples/js-examples/statement/meta.json
- live-examples/js-examples/statement/statement-forawaitof.html
This PR aims to add a new example for `for await...of` as a supporting example for the `for await...of` statement MDN docs page.
> Adding for await of statement example

- live-examples/js-examples/array/array-slice.js
Adding a `slice()` example to demonstrate a full shallow copy of the array.
> Add an example of slice without arguments

- live-examples/js-examples/number/number-toprecision.js
Number.parseFloat here serves only to distract from the use of toPrecision.
> Remove use of Number.parseFloat in toPrecision example

- live-examples/js-examples/array/array-reduce.js
Goal: `reduce` is often a confusing method for new learners, and we hope that this more explicit example will help build understanding.
Other array methods (`map`, `sort`, `filter`, `forEach`) all use inline arrow functions for their intro examples, but reduce does not. This PR makes the first example shown for `reduce`  follow that same convention. It also uses variable naming to communicate what has changed between the two examples.
The downside of this change is that the example is longer, but we think it's easier to understand now for beginners.
**Alternatives considered**
Examples would be shorter and more readable if we dropped `Value` from the parameter names (`currentValue` becomes `current`). However, that would not match the rest of the page's prose and examples, so we left the …
> Improve Array.prototype.reduce intro example

- live-examples/css-examples/text/white-space.css
Fixes #2031 by setting border instead of background. All examples are now clearly visible in both light and dark mode.
> Fix for white-space in Dark Mode

- live-examples/css-examples/backgrounds-and-borders/box-shadow.css
Now text is visible in both dark and light mode.
It was reported in Issue ~~#2031~~ #2032
Fixes #2032.
> Fix for box-shadow in Dark Mode

- live-examples/css-examples/basic-user-interface/text-overflow.css
text-overflow should now be visible in both dark and light mode. It was reported in #2031 and #2030
> Fix for text-overflow in Dark Mode

- live-examples/css-examples/backgrounds-and-borders/border-bottom.html
- live-examples/css-examples/backgrounds-and-borders/border-color.css
- live-examples/css-examples/backgrounds-and-borders/border-image.css
- live-examples/css-examples/backgrounds-and-borders/border-left.html
- live-examples/css-examples/backgrounds-and-borders/border-right.html
- live-examples/css-examples/backgrounds-and-borders/border-style.css
- live-examples/css-examples/backgrounds-and-borders/border-top.html
- live-examples/css-examples/backgrounds-and-borders/border-width.css
- live-examples/css-examples/backgrounds-and-borders/border.css
- live-examples/css-examples/backgrounds-and-borders/border.html
- live-examples/css-examples/logical-properties/border-color.css
- live-examples/css-examples/logical-properties/border-style.css
- live-examples/css-examples/logical-properties/border-width.css
- live-examples/css-examples/logical-properties/border.css
I have made changes to most of CSS border properties, to fix their visibility on new Dark Theme.
In border-color, border-image & border-width, text is now black.
In border-style properties, text color is now black and border-color is brown.
In border shorthands, text color and default border color is now darkmagenta, border-color of last example was changed from violet to lemon.
> Fixed text color in dark mode for CSS border

- live-examples/js-examples/intl/intl-getcanonicallocales.js
Hello folks, sorry I couldn't find guidelines for creating PRs.
I was looking at the documentation for Intl and found this (notice the error is not displayed):
After stringifying the error:
> Stringify error (Intl - getCanonicalLocales)

- live-examples/css-examples/positioned-layout/position.html
In [position](https://developer.mozilla.org/en-US/docs/Web/CSS/position) property, having -webkit-sticky seems unnecessary. It clutters example, while non-prefixed version seems to be working everywhere anyway.
> Removed vendor prefix from position: sticky

- live-examples/css-examples/lists/list-style.css
Removes static white background for lists causing the text not to be visible in dark mode.
Fixes mdn/content#14036
> Remove static white background, fix for dark mode

- live-examples/js-examples/intl/intl-segmenter-prototype-resolvedoptions.js
- live-examples/js-examples/intl/intl-segmenter-prototype-segment.js
- live-examples/js-examples/intl/intl-segmenter-supportedlocalesof.js
- live-examples/js-examples/intl/intl-segmenter.js
- live-examples/js-examples/intl/intl-segments-prototype-@@iterator.js
- live-examples/js-examples/intl/intl-segments-prototype-containing.js
- live-examples/js-examples/intl/meta.json
As a companion for https://github.com/mdn/content/pull/8402
> Initial set of live examples for Intl.Segmenter et al.

- live-examples/css-examples/text/overflow-wrap.css
It's a fix for #2054 in which contrast was an issue. I have replaced background and border with same values as in [grid-row](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row), which looks quite well.
> Fix contrast in overflow-wrap

- live-examples/css-examples/cascading-and-inheritance/all.html
A new global keyword was introduced in FF97, the `revert-layer` keyword.
The `all` property can now have another value `revert-layer` in addition to `initial`, `inherit`, `unset`, and `revert`.
This PR updates the interactive example to:
- Add `all: revert` (was missing)
- Add `all: revert-layer` (new)
- Reorder values to match the order `initial`, `inherit`, `unset`, `revert`, `revert-layer` as in "Syntax"
- Switch `initial-choice="true"` to  `initial`
Content issue tracking this work: https://github.com/mdn/content/issues/13373
PR for the new `revert-layer` page: https://github.com/mdn/content/pull/14287
PR for `revert-layer` changes to `all` property page: https://github.com/mdn/content/pull/14414
> Update interactive example for "all" to add "revert" and "revert-layer"

- live-examples/js-examples/expressions/expressions-voidoperator.js
Fixes https://github.com/mdn/content/issues/14361.
As discussed in issue [#14361](https://github.com/mdn/content/issues/14361), exception output currently shows "Object {  }" which causes misunderstandings. Change to "e.toString()" will print "ReferenceError: test is not defined"
> Rewrite void operator example

- live-examples/css-examples/text-decoration/text-emphasis-color.css
- live-examples/css-examples/text-decoration/text-emphasis-color.html
- live-examples/css-examples/text-decoration/text-emphasis-position.css
- live-examples/css-examples/text-decoration/text-emphasis-position.html
- live-examples/css-examples/text-decoration/text-emphasis-style.html
- live-examples/css-examples/text-decoration/text-emphasis.html
See https://github.com/mdn/content/pull/14542
The example at https://github.com/mdn/interactive-examples/blob/d9e7dcae46e1dbbd0207f89628f8660328402978/CONTRIBUTING-CSS.md#supporting-prefixed-properties might need to be reworded or updated, as `text-emphasis` won't be longer a good example for that case.
> Remove -webkit-text-emphasis as it's now unprefixed

- live-examples/css-examples/backgrounds-and-borders/border-end-end-radius.html
- live-examples/css-examples/backgrounds-and-borders/border-end-start-radius.html
- live-examples/css-examples/backgrounds-and-borders/border-start-end-radius.html
- live-examples/css-examples/backgrounds-and-borders/border-start-start-radius.html
- live-examples/css-examples/backgrounds-and-borders/meta.json
Added interactive examples of [border-start-start-radius](https://developer.mozilla.org/en-US/docs/Web/CSS/border-start-start-radius), [border-start-end-radius](https://developer.mozilla.org/en-US/docs/Web/CSS/border-start-end-radius), [border-end-start-radius](https://developer.mozilla.org/en-US/docs/Web/CSS/border-end-start-radius) & [border-end-end-radius](https://developer.mozilla.org/en-US/docs/Web/CSS/border-end-end-radius). Visually they are pretty much the same as other border-radius properties, but I added writing-mode & direction too.
> Adds 4 border-radius properties

- live-examples/css-examples/backgrounds-and-borders/border-style.css
Explicitly set interactive example output bg to `#fff`
fixes mdn/content#14580
> Explicitly set interactive example output bg to #fff

- live-examples/css-examples/text/meta.json
- live-examples/css-examples/text/ruby-position.css
- live-examples/css-examples/text/ruby-position.html
Adds [ruby-position](https://developer.mozilla.org/en-US/docs/Web/CSS/ruby-position) property.
Value `alternate` is supported only on firefox, so I skipped it for now.
Text comes from [ruby html element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ruby).
> ruby-position

- live-examples/html-examples/input/radio.html
The fieldset and legend are required for accessibility. My concern is that some developers will copy the example without the needed fieldset/legend.
> Use a fieldset within the input/radio example

- live-examples/css-examples/scroll-snap/scroll-margin-inline.html
I added better examples to [scroll-margin-inline](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-inline), so it is ready to be added to mdn/content.
> Improve scroll-margin-inline

- live-examples/css-examples/text/meta.json
- live-examples/css-examples/text/user-select.css
- live-examples/css-examples/text/user-select.html
I have added interactive example for [user-select](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) property.
I have also changed 3 names in this meta.json, which used "-" as a word separator instead of using camelCase.
> user-select

- live-examples/css-examples/positioned-layout/inset-block-end.html
- live-examples/css-examples/positioned-layout/inset-block-start.html
- live-examples/css-examples/positioned-layout/inset-block.html
- live-examples/css-examples/positioned-layout/inset-inline-end.html
- live-examples/css-examples/positioned-layout/inset-inline-start.html
- live-examples/css-examples/positioned-layout/inset-inline.html
- live-examples/css-examples/positioned-layout/inset.css
- live-examples/css-examples/positioned-layout/inset.html
- live-examples/css-examples/positioned-layout/meta.json
Those are interactive examples for [inset](https://developer.mozilla.org/en-US/docs/Web/CSS/inset), [inset-block](https://developer.mozilla.org/en-US/docs/Web/CSS/inset-block), [inset-block-end](https://developer.mozilla.org/en-US/docs/Web/CSS/inset-block-end), [inset-block-start](https://developer.mozilla.org/en-US/docs/Web/CSS/inset-block-start), [inset-inline](https://developer.mozilla.org/en-US/docs/Web/CSS/inset-inline), [inset-inline-end](https://developer.mozilla.org/en-US/docs/Web/CSS/inset-inline-end), [inset-inline-start](https://developer.mozilla.org/en-US/docs/Web/CSS/inset-inline-start) properties.
Example text and style is copied from [top](https://developer.mozilla.org/en-US/docs/Web/CSS/top).
> All inset properties

- live-examples/css-examples/basic-user-interface/appearance.html
As requested in Issue [#11278](https://github.com/mdn/content/issues/11278), appearance examples now have visual effect. Current standard contains only 4 keywords: none, auto, menulist-button & textfield. I have changed example to button, on which none and auto have an effect(border changes). Unfortunately I don't know any element on which menulist-button and textfield have any visual impact, so I have removed them from examples.
> appearance

- live-examples/css-examples/text-decoration/text-emphasis-position.html
Currently firefox requires both keywords( [ over | under ] && [ right | left ] ) to be specified in [text-emphasis-position](https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-position), so I added them to example and also added vertical writing mode examples so meaning of right/left is shown. Chrome recently added support for this property along with [text-emphasis-color](https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-color) & [text-emphasis-style](https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-style), so we will be able to add all 3 of them to content.
> Fix text-emphasis-position

- live-examples/css-examples/writing-modes/meta.json
- live-examples/css-examples/writing-modes/text-combine-upright.css
- live-examples/css-examples/writing-modes/text-combine-upright.html
Interactive Example for property [text-combine-upright](https://developer.mozilla.org/en-US/docs/Web/CSS/text-combine-upright).
> text-combine-upright

- live-examples/css-examples/fonts/font-synthesis.css
- live-examples/css-examples/fonts/font-synthesis.html
Current version of font-synthesis usually doesn't give any visual effect, because used fonts had bold, italic and small-caps styles. I have attached fonts from fonts.google.com, that don't have those styles, so they will always be shown as intended. Also text "italic" was changed to "small-caps".
Unfortunately on Chrome, only small-caps value seems to be working, even though all of them are recognized. Example has visual effect, but bold and italic styles are always active:
> Fix font-synthesis example

- CONTRIBUTING-CSS.md
See https://github.com/mdn/interactive-examples/pull/2073 - `text-emphasis` is no longer prefixed, so it's not a good example. This PR switches it for `box-decoration-break`, which is still prefixed.
> docs: Change prefixed property example in meta-docs

- live-examples/js-examples/string/string-endswith.js
These examples were quite confusing. As a user I expect the easy,
obvious example first, not an example with a "gotcha". And unfortunately
both of these examples were "gotchas", or best case scenario they
illustrated the more complicated things one can do with
string.endsWith(), but such examples should come _after_ the simple
ones.
> fix: Clarify string-endswith examples

- .github/workflows/deploy.yml
Currently, the deploy workflow will still run on every push to main.
This, hopefully, will change this to only run for pushes to main that is labelled `release`
fix #2138
> fix: only run deploy action if labeled release

- .github/workflows/publish-release.yml
Even though `act` complains about the missing `runs-on` for the reusable action, GitHub does not like it.
> fix: remove runs-on

- live-examples/js-examples/statement/meta.json
- live-examples/js-examples/statement/statement-forawaitof.js
Switched `for await of` example to use a `.js` file and `.html`
fix #2147
> fix: use js file not html for js examples

- live-examples/js-examples/intl/intl-numberformat-prototype-formattoparts.js
- live-examples/js-examples/intl/meta.json
#1649 
I took the `Intl.NumberFormat` parts from [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat), and the `formatToParts` parts from [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/formatToParts)
> Added Intl.NumberFormat.formatToParts() example

- live-examples/js-examples/functions/functions-restparameters.js
reduce() can be confusing for new users, it's better to use a simple for loop here.
> Remove reduce function from restparameters example

- live-examples/wat-examples/variables/global.wat
Fixes an error when running the live example at https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/Variables/Global
```
> Error: parseWat failed:
8:20: error: imports must occur before all non-import definitions
(global $from_js (import "env" "from_js") i32)
^
```
This moves the imported global to above the created global.
> Fix syntax error (put imports first)

- live-examples/wat-examples/numeric/trunc.wat
- While browsing the [Truncate docs on MDN](https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/Numeric/Truncate), I noticed that the example was not calling `f32.trunc`, but rather it was calling `f32.ceil`
- This pull request simply fixes the call
> Fix Wasm trunc example

- live-examples/css-examples/cascading-and-inheritance/all.css
- live-examples/css-examples/cascading-and-inheritance/all.html
Current example for property [all](https://developer.mozilla.org/en-US/docs/Web/CSS/all) doesn't show any difference between values inherit, unset, revert and revert-layer. I have improved example so difference between inherit, unset and revert is visible. Still revert and revert-layer will look the same, because rever-layer requires cascade layers in order to have any impact. Maybe it's better to remove it from this example and make example in layers in [revert-layer](https://developer.mozilla.org/en-US/docs/Web/CSS/revert-layer) page? Scrollbar would be gone too.
> Improve example of property all

- live-examples/css-examples/pseudo-element/file-selector-button.css
- live-examples/css-examples/pseudo-element/file-selector-button.html
- live-examples/css-examples/pseudo-element/first-letter.css
- live-examples/css-examples/pseudo-element/first-letter.html
- live-examples/css-examples/pseudo-element/first-line.css
- live-examples/css-examples/pseudo-element/first-line.html
- live-examples/css-examples/pseudo-element/meta.json
- live-examples/css-examples/pseudo-element/placeholder.css
- live-examples/css-examples/pseudo-element/placeholder.html
- live-examples/css-examples/pseudo-element/selection.css
- live-examples/css-examples/pseudo-element/selection.html
Added interactive examples to pseudo elements [::file-selector-button](https://developer.mozilla.org/en-US/docs/Web/CSS/::file-selector-button), [::first-letter](https://developer.mozilla.org/en-US/docs/Web/CSS/::first-letter), [::first-line](https://developer.mozilla.org/en-US/docs/Web/CSS/::first-line), [::placeholder](https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder) and [::selection](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection).
> Few pseudo elements

- live-examples/css-examples/fonts/font-variant-east-asian.css
This commit was proposed by @mfuji09 in #2129 to fix [font-variant-east-asian](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-east-asian) example on MacOS. @wbamberg Could you please check if you see any visual difference between property values now?
On windows it's like that:
> MacOS fix in font-variant-east-asian
