mdn/interactive-examples

js/editable-js.js

I think this should be a fix for https://github.com/mdn/interactive-examples/issues/253.

Write error message to the output

---

live-examples/js-examples/sharedarraybuffer-bytelength.html
live-examples/js-examples/sharedarraybuffer-constructor.html
live-examples/js-examples/sharedarraybuffer-slice.html
site.json

No conflicts this time. Hopefully I'm doing it right? :)
On the slice example I wondered whether to populate the entire view but I think we'd need a loop to do this. Open to suggestions though.

added SharedArrayBuffer examples

---

live-examples/js-examples/atomics-add.html
live-examples/js-examples/atomics-and.html
live-examples/js-examples/atomics-compareexchange.html
live-examples/js-examples/atomics-exchange.html
live-examples/js-examples/atomics-islockfree.html
live-examples/js-examples/atomics-load.html
live-examples/js-examples/atomics-or.html
live-examples/js-examples/atomics-store.html
live-examples/js-examples/atomics-sub.html
live-examples/js-examples/atomics-xor.html
site.json

Note I missed a couple out such as wait and wake as it was difficult to create satisfactory examples.

added Atomics examples

---

live-examples/js-examples/promise-all.html
live-examples/js-examples/promise-catch.html
live-examples/js-examples/promise-constructor.html
live-examples/js-examples/promise-race.html
live-examples/js-examples/promise-reject.html
live-examples/js-examples/promise-resolve.html
live-examples/js-examples/promise-then.html
site.json

Promised promise examples as promised :)

promise examples

---

live-examples/js-examples/globalprops-decodeuri.html
live-examples/js-examples/globalprops-decodeuricomponent.html
live-examples/js-examples/globalprops-encodeuri.html
live-examples/js-examples/globalprops-encodeuricomponent.html
live-examples/js-examples/globalprops-eval.html
live-examples/js-examples/globalprops-infinity.html
live-examples/js-examples/globalprops-isfinite.html
live-examples/js-examples/globalprops-isnan.html
live-examples/js-examples/globalprops-nan.html
live-examples/js-examples/globalprops-null.html
live-examples/js-examples/globalprops-parsefloat.html
live-examples/js-examples/globalprops-parseint.html
live-examples/js-examples/globalprops-undefined.html
site.json

I'm undecided whether the examples for eval, infinity, null etc are the best approach. Pushed here for discussion.

global properties

---

live-examples/js-examples/expressions-arithmetic.html
live-examples/js-examples/expressions-assignment.html
live-examples/js-examples/expressions-bitwiseoperators.html
live-examples/js-examples/expressions-classexpression.html
live-examples/js-examples/expressions-commaoperators.html
live-examples/js-examples/expressions-comparisonoperators.html
live-examples/js-examples/expressions-conditionaloperators.html
live-examples/js-examples/expressions-deleteoperator.html
live-examples/js-examples/expressions-destructuringassignment.html
live-examples/js-examples/expressions-functionasteriskexpression.html
live-examples/js-examples/expressions-functionexpression.html
live-examples/js-examples/expressions-groupingoperator.html
live-examples/js-examples/expressions-inoperator.html
live-examples/js-examples/expressions-instanceof.html
live-examples/js-examples/expressions-logicaloperator.html
live-examples/js-examples/expressions-newoperator.html
live-examples/js-examples/expressions-newtarget.html
live-examples/js-examples/expressions-objectinitializer.html
live-examples/js-examples/expressions-operatorprecedence.html
live-examples/js-examples/expressions-propertyaccessors.html
live-examples/js-examples/expressions-spreadsyntax.html
live-examples/js-examples/expressions-this.html
live-examples/js-examples/expressions-typeof.html
live-examples/js-examples/expressions-voidoperator.html
live-examples/js-examples/expressions-yield.html
live-examples/js-examples/expressions-yieldasterisk.html
site.json

Not sure about the file naming conventions for these examples.
Note that where I couldn't think of an alternative some examples are effectively a series of console logs.
Conceivably I could make the arithmetic example simpler - I'm maybe trying to kill too many birds there.

JS expression and operator examples

---

live-examples/js-examples/boolean-constructor.html
live-examples/js-examples/boolean-tostring.html
live-examples/js-examples/boolean-valueof.html
live-examples/js-examples/function-apply.html
live-examples/js-examples/function-bind.html
live-examples/js-examples/function-call.html
live-examples/js-examples/function-constructor.html
live-examples/js-examples/function-length.html
live-examples/js-examples/function-name.html
live-examples/js-examples/function-tostring.html
live-examples/js-examples/functions-arguments.html
live-examples/js-examples/functions-arrow.html
live-examples/js-examples/functions-default.html
live-examples/js-examples/functions-definitions.html
live-examples/js-examples/functions-getter.html
live-examples/js-examples/functions-restparameters.html
live-examples/js-examples/functions-setter.html
live-examples/js-examples/json-parse.html
live-examples/js-examples/json-stringify.html
site.json

Boolean, Function(s) and JSON JS Examples

---

live-examples/js-examples/statement-async.html
live-examples/js-examples/statement-block.html
live-examples/js-examples/statement-break.html
live-examples/js-examples/statement-class.html
live-examples/js-examples/statement-const.html
live-examples/js-examples/statement-continue.html
live-examples/js-examples/statement-default.html
live-examples/js-examples/statement-dowhile.html
live-examples/js-examples/statement-empty.html
live-examples/js-examples/statement-for.html
live-examples/js-examples/statement-forin.html
live-examples/js-examples/statement-forof.html
live-examples/js-examples/statement-function.html
live-examples/js-examples/statement-functionasterisk.html
live-examples/js-examples/statement-ifelse.html
live-examples/js-examples/statement-label.html
live-examples/js-examples/statement-let.html
live-examples/js-examples/statement-return.html
live-examples/js-examples/statement-switch.html
live-examples/js-examples/statement-throw.html
live-examples/js-examples/statement-trycatch.html
live-examples/js-examples/statement-var.html
live-examples/js-examples/statement-while.html
site.json

There's a bit of overlap with the Expressions Examples but I think that's ok.
The Async example is a little large - any ideas on how to reduce this is welcome :)

JS Statements and Declarations Examples

---

live-examples/js-examples/number-epsilon.html
live-examples/js-examples/number-isfinite.html
live-examples/js-examples/number-isinteger.html
live-examples/js-examples/number-isnan.html
live-examples/js-examples/number-issafeinteger.html
live-examples/js-examples/number-max-safe-integer.html
live-examples/js-examples/number-max-value.html
live-examples/js-examples/number-min-safe-integer.html
live-examples/js-examples/number-min-value.html
live-examples/js-examples/number-nan.html
live-examples/js-examples/number-negative-infinity.html
live-examples/js-examples/number-parsefloat.html
live-examples/js-examples/number-parseint.html
live-examples/js-examples/number-positive-infinity.html
live-examples/js-examples/number-toexponential.html
live-examples/js-examples/number-tofixed.html
live-examples/js-examples/number-tolocalestring.html
live-examples/js-examples/number-toprecision.html
live-examples/js-examples/number-tostring.html
live-examples/js-examples/number-valueof.html
site.json

number examples

---

live-examples/js-examples/set-prototype-@@iterator.html
live-examples/js-examples/set-prototype-add.html
live-examples/js-examples/set-prototype-clear.html
live-examples/js-examples/set-prototype-constructor.html
live-examples/js-examples/set-prototype-delete.html
live-examples/js-examples/set-prototype-entries.html
live-examples/js-examples/set-prototype-foreach.html
live-examples/js-examples/set-prototype-has.html
live-examples/js-examples/set-prototype-size.html
live-examples/js-examples/set-prototype-values.html
live-examples/js-examples/weakset-prototype-add.html
live-examples/js-examples/weakset-prototype-delete.html
live-examples/js-examples/weakset-prototype-has.html
site.json

Similar but different to Map and WeakMap :)
To think about:
Should we instantiate an object with `object1 = new Object()` or `object1 = {}` ?

JS Set and WeakSet Prototype Examples

---

live-examples/js-examples/symbol-constructor.html
live-examples/js-examples/symbol-for.html
live-examples/js-examples/symbol-hasinstance.html
live-examples/js-examples/symbol-isconcatspreadable.html
live-examples/js-examples/symbol-iterator.html
live-examples/js-examples/symbol-keyfor.html
live-examples/js-examples/symbol-match.html
live-examples/js-examples/symbol-prototype-tostring.html
live-examples/js-examples/symbol-prototype.html
live-examples/js-examples/symbol-replace.html
live-examples/js-examples/symbol-search.html
live-examples/js-examples/symbol-species.html
live-examples/js-examples/symbol-split.html
live-examples/js-examples/symbol-toprimitive.html
live-examples/js-examples/symbol-tostringtag.html
live-examples/js-examples/symbol-unscopables.html
site.json

Note - I couldn't think (or find) any suitable examples for:
- Symbol.prototype.valueOf()
- Symbol.prototype[@@toPrimitive]

JS Symbol Examples

---

Jenkinsfile

http://docs.aws.amazon.com/cli/latest/reference/s3/sync.html

Add cache-control args to s3 sync to fix #311

---

live-examples/css-examples/font.html

Just choose a more obvious initial example.

font update: choose a more distinctive initial example

---

Jenkinsfile
bin/s3-sync.sh

This is based on the @jwhitlock's proposal in #334. This is WIP, has not yet been tested, and is intended to further the discussion with a concrete example implementation.

Set different cache times for different assets to fix #334

---

package-lock.json
package.json

This commit appears to have skipped master

merge prod into master

---

CONTRIBUTING.md

After submitting my first PR, I didn't get this attribute (even though it's pretty self-explanatory :/) so here is a one-liner :)

Clarify a bit the initial-choice attribute

---

live-examples/css-examples/box-sizing.html
live-examples/css-examples/object-fit.html
live-examples/css-examples/text-decoration.html
live-examples/css-examples/text-overflow.html
live-examples/css-examples/word-break.html

I noticed that several of these were wrong. I hope they are corrected in this PR.

Fix data-property values

---

live-examples/css-examples/css/font-family.css
live-examples/css-examples/font-family.html
site.json

I've tried to make this reasonably close to the existing `font` example.

Add font-family example

---

live-examples/css-examples/css/padding.css
live-examples/css-examples/padding.html
site.json

Again, happy to get feedback on this very simple example.

Add padding example

---

live-examples/css-examples/css/font-style.css
live-examples/css-examples/font-style.html
site.json

Use the same text as the other `font` examples, and choose a font that has a more interesting italic style.

Update font-style example

---

live-examples/css-examples/css/margin.css
live-examples/css-examples/margin.html
site.json

This is a pretty simple example, feedback welcome!

Add margin example

---

site.json

I think we are probably not very consistent about these, so we should probably go through all of site.json. But these ones in particular were bugging me today...

Fix titles for Function examples

---

site.json

Fix a typo in site.json

---

site.json

Fixes the issues #395, #396, #397, #398, #399.

Fixed the demo titles

---

live-examples/css-examples/css/text-decoration-skip-ink.css
live-examples/css-examples/text-decoration-skip-ink.html
site.json

Add demo for text-decoration-skip-ink

---

live-examples/js-examples/statement-switch.html

I think this provides better clarity, and it aligns them the way that they are elsewhere in the page.

Indents the break statements

---

live-examples/js-examples/array-sort.html
live-examples/js-examples/array-splice.html
live-examples/js-examples/array-tolocalestring.html
site.json

- Array.toLocaleString() - Fixes #420 
- Array.splice() - Fixes #419

Add demo for Array.prototypes Fixes #420, #419

---

live-examples/js-examples/expressions-functionexpression.html

Fix for https://github.com/mdn/interactive-examples/issues/431

Fix function expression example

---

__tests__/console-utils.test.js
js/editor-libs/console-utils.js

Enhance formatObject to support formatting actual object

---

live-examples/js-examples/array-keys.html
live-examples/js-examples/array-reverse.html
site.json

#415 Add example for Array.prototype.reverse
#414 Add example for Array.prototype.keys

Added examples for Array.prototype.reverse and  Array.prototype.keys

---

live-examples/css-examples/border-style.html
live-examples/css-examples/css/border-style.css

Update `border-style` example

---

live-examples/css-examples/css/text-transform.css
live-examples/css-examples/text-transform.html
site.json

Add `text-transform` example

---

live-examples/js-examples/array-foreach.html
site.json

Adding interactive demo for Array.forEach(). Fixes #413 
I am not yet very used to contributing, so any advice or comment is appreciated :)

Add interactive demo for Array.forEach(). Fixes #413

---

live-examples/js-examples/date-setutcmilliseconds.html
live-examples/js-examples/date-setutcminutes.html
live-examples/js-examples/date-setutcseconds.html
site.json

Fixes #393, #392, #391, #390, #388, #387

Add UTC set examples for Minutes,Milliseconds and Seconds

---

css/editable-js.css
live-examples/js-examples/date-getdate.html
live-examples/js-examples/date-getday.html
live-examples/js-examples/date-getfullyear.html
live-examples/js-examples/date-gethours.html
live-examples/js-examples/date-getmilliseconds.html
live-examples/js-examples/date-getminutes.html
live-examples/js-examples/date-getmonth.html
live-examples/js-examples/date-getseconds.html
live-examples/js-examples/date-gettime.html
live-examples/js-examples/date-getutcmilliseconds.html
live-examples/js-examples/date-getutcseconds.html

Add .shorter css class for shorter JS examples

---

live-examples/css-examples/background-color.html

Remove example 7 (to avoid vertical scrollbar: I thought this was the best one to omit) and comments (to avoid horizontal scrollbars).

Update background-color example to avoid scrollbars

---

live-examples/css-examples/border-bottom-color.html
live-examples/css-examples/border-color.html
live-examples/css-examples/border-left-color.html
live-examples/css-examples/border-right-color.html
live-examples/css-examples/border-top-color.html
live-examples/css-examples/css/border-top-color.css
site.json

Add `border-*-color` examples

---

live-examples/css-examples/border-bottom-style.html
live-examples/css-examples/border-left-style.html
live-examples/css-examples/border-right-style.html
live-examples/css-examples/border-top-style.html
site.json

Add `border-*-style` examples

---

live-examples/css-examples/border-bottom.html
live-examples/css-examples/border-left.html
live-examples/css-examples/border-right.html
live-examples/css-examples/border-top.html
live-examples/css-examples/border.html
live-examples/css-examples/css/border.css
site.json

Add `border` examples

---

live-examples/css-examples/text-decoration/meta.json
live-examples/css-examples/text-decoration/text-decoration-color.css
live-examples/css-examples/text-decoration/text-decoration-color.html

Add `text-decoration-color` example

---

.eslintrc.js
__tests__/console-utils.test.js
js/editor-libs/console-utils.js

Because String object is different from string literal
Also restructure tests as nested suites
Fixes #293

Handle String object at formatObject

---

live-examples/css-examples/table/border-collapse.css
live-examples/css-examples/table/border-collapse.html
live-examples/css-examples/table/meta.json

Add `border-collapse` example

---

css/editor-libs/tabbed-editor-common.css
css/tabbed-editor.css
index.js
js/editor.js
js/mode/htmlmixed/htmlmixed.js
js/mode/xml/xml.js
lib/bundler.js
lib/config.js
lib/pageBuilder.js
lib/processor.js
lib/utils.js
live-examples/html-examples/blockquote.html
live-examples/html-examples/meta.json
live-examples/html-examples/table.html
package.json
site.json
tmpl/live-html-tmpl.html

This is the first alpha version to get HTML examples into the build pipeline. After @kenrick95 latest PR merges, I need to update this and will then open a PR for the tabbed UI for HTML examples.

Adds the first iteration of HTML examples

---

live-examples/js-examples/expressions/expressions-classexpression.html

Currently, we use a class declaration.
```
class Rectangle {
constructor(height, width) {
this.height = height;
this.width = width;
}
area() {
return this.height * this.width;
}
}
console.log(new Rectangle(5,8).area());
// expected output: 40
```
after
```
var Rectangle = class {
constructor(height, width) {
this.height = height;
this.width = width;
}
area() {
return this.height * this.width;
}
}
console.log(new Rectangle(5,8).area());
// expected output: 40
```

Update class expression example

---

live-examples/css-examples/transforms/meta.json
live-examples/css-examples/transforms/perspective.html
live-examples/css-examples/transforms/rotate.html
live-examples/css-examples/transforms/rotate3d.css
live-examples/css-examples/transforms/rotate3d.html
live-examples/css-examples/transforms/rotateX.html
live-examples/css-examples/transforms/rotateY.html
live-examples/css-examples/transforms/rotateZ.html
live-examples/css-examples/transforms/scale.html
live-examples/css-examples/transforms/scale3d.html
live-examples/css-examples/transforms/scaleX.html
live-examples/css-examples/transforms/scaleY.html
live-examples/css-examples/transforms/scaleZ.html
live-examples/css-examples/transforms/skew.html
live-examples/css-examples/transforms/skewX.html
live-examples/css-examples/transforms/skewY.html
live-examples/css-examples/transforms/transform3d.css
live-examples/css-examples/transforms/translate.css
live-examples/css-examples/transforms/translate.html
live-examples/css-examples/transforms/translate3d.html
live-examples/css-examples/transforms/translateX.html
live-examples/css-examples/transforms/translateY.html
live-examples/css-examples/transforms/translateZ.html

Includes all `<transform-function>` types except for the matrix ones.

Add transform function examples

---

live-examples/css-examples/table/border-spacing.css
live-examples/css-examples/table/border-spacing.html
live-examples/css-examples/table/caption-side.css
live-examples/css-examples/table/caption-side.html
live-examples/css-examples/table/empty-cells.css
live-examples/css-examples/table/empty-cells.html
live-examples/css-examples/table/meta.json
live-examples/css-examples/table/table-layout.css
live-examples/css-examples/table/table-layout.html

Includes `border-spacing`, `caption-side`, `empty-cells`, and `table-layout`.

Add table examples

---

live-examples/css-examples/transitions/meta.json
live-examples/css-examples/transitions/transition-delay.html
live-examples/css-examples/transitions/transition-duration.html
live-examples/css-examples/transitions/transition-property.html
live-examples/css-examples/transitions/transition-timing-function.html
live-examples/css-examples/transitions/transition.css
live-examples/css-examples/transitions/transition.html

Here's an attempt at an example for `transition`.
It's pretty much an interactivisation of the existing example in the page: https://developer.mozilla.org/en-US/docs/Web/CSS/transition

Add transition example

---

live-examples/css-examples/backgrounds-and-borders/border-radius.css
live-examples/css-examples/backgrounds-and-borders/border-radius.html
live-examples/css-examples/backgrounds-and-borders/meta.json

Adding a new PR with changes recommended by @wbamberg for #502

Adding border radius example with recommended changes.

---

.all-contributorsrc

Would you mind adding me as a code contributor? Thanks!

Add contribution item

---

live-examples/css-examples/text/hyphens.css
live-examples/css-examples/text/hyphens.html
live-examples/css-examples/text/letter-spacing.html
live-examples/css-examples/text/meta.json
live-examples/css-examples/text/word-spacing.html

This includes `hyphens`, `letter-spacing`, and `word-spacing`.

Add various text examples

---

live-examples/css-examples/multi-column-layout/column-count.css
live-examples/css-examples/multi-column-layout/column-count.html
live-examples/css-examples/multi-column-layout/column-fill.css
live-examples/css-examples/multi-column-layout/column-fill.html
live-examples/css-examples/multi-column-layout/column-gap.css
live-examples/css-examples/multi-column-layout/column-gap.html
live-examples/css-examples/multi-column-layout/column-rule-color.html
live-examples/css-examples/multi-column-layout/column-rule-style.html
live-examples/css-examples/multi-column-layout/column-rule-width.html
live-examples/css-examples/multi-column-layout/column-rule.css
live-examples/css-examples/multi-column-layout/column-rule.html
live-examples/css-examples/multi-column-layout/column-width.css
live-examples/css-examples/multi-column-layout/column-width.html
live-examples/css-examples/multi-column-layout/columns.css
live-examples/css-examples/multi-column-layout/columns.html
live-examples/css-examples/multi-column-layout/meta.json

This includes `column-count`, `column-fill`, `column-gap`, `column-rule-color`,`column-rule-style`,`column-rule-width`, `column-rule`, `column-width`, and `columns`.

Add column examples

---

live-examples/css-examples/basic-box-model/meta.json
live-examples/css-examples/basic-box-model/width.css
live-examples/css-examples/basic-box-model/width.html

I've created the interactive example based on the four blue boxes as per #565 
This is my first ever pull request so I hope everything's alright. I'm pleased to take any feedback.

CSS interactive examples: Add example for width.

---

live-examples/css-examples/lists/list-style-position.css
live-examples/css-examples/lists/list-style-position.html
live-examples/css-examples/lists/meta.json

Hello. My very first pull request for mdn. I hope everything is alright. Pull's related to #481 
I've made two lists ul and ol to highlight that list-style-position works for both.
Looking forward to the feedback (especially on how to make it prettier).

Add `list-style-position` css example

---

live-examples/css-examples/basic-box-model/margin-bottom.html
live-examples/css-examples/basic-box-model/margin-left.css
live-examples/css-examples/basic-box-model/margin-left.html
live-examples/css-examples/basic-box-model/margin-right.html
live-examples/css-examples/basic-box-model/margin-top.html
live-examples/css-examples/basic-box-model/margin.css
live-examples/css-examples/basic-box-model/meta.json

Add `margin-*` examples

---

live-examples/css-examples/color/color.html
live-examples/css-examples/color/opacity.html
live-examples/css-examples/fonts/font-size.css
live-examples/css-examples/fonts/font-size.html
live-examples/css-examples/fonts/meta.json

As per this issue 
https://github.com/mdn/interactive-examples/issues/563

add css font-size examples

---

live-examples/css-examples/logical-properties/block-size.css
live-examples/css-examples/logical-properties/max-block-size.html
live-examples/css-examples/logical-properties/max-inline-size.html
live-examples/css-examples/logical-properties/meta.json
live-examples/css-examples/logical-properties/min-block-size.html
live-examples/css-examples/logical-properties/min-inline-size.html
live-examples/css-examples/logical-properties/offset-block-end.css
live-examples/css-examples/logical-properties/offset-block-end.html
live-examples/css-examples/logical-properties/offset-block-start.css
live-examples/css-examples/logical-properties/offset-block-start.html
live-examples/css-examples/logical-properties/offset-inline-end.css
live-examples/css-examples/logical-properties/offset-inline-end.html
live-examples/css-examples/logical-properties/offset-inline-start.css
live-examples/css-examples/logical-properties/offset-inline-start.html

The offset properties are a little tricky to show as to change the value of the property and see the change in direction requires changing two things (the abspos item AND the writing mode of the container). I have therefore chosen to change the writing mode, and detail in the example what setting the abspos item has.
Though if anyone has a better solution, I'm happy to change it!

Remaining logical properties, min and max, offsets

---

live-examples/html-examples/css/datalist.css
live-examples/html-examples/datalist.html
live-examples/html-examples/table.html

This contains some editorial changes that keep the width down to a point where the editor doesn't overflow when the window is 900px wide, which I hope will be enough (full-width on my screen is a bit over 1000px).

Trim example sizes

---

live-examples/html-examples/css/select.css
live-examples/html-examples/meta.json
live-examples/html-examples/select.html

I chose select because it was one of the elements most often cited in the survey responses.

Add example for select

---

live-examples/html-examples/audio.html
live-examples/html-examples/css/audio.css
live-examples/html-examples/meta.json

I chose audio because it was one of the elements most often mentioned in the survey.
The audio file is public domain: http://soundbible.com/tags-animal.html.

Added audio element example

---

css/tabbed-editor.css

Give the output pane a fixed width of 40%.

Give output 40% always

---

live-examples/css-examples/animation/animation-direction.css
live-examples/css-examples/animation/animation-direction.html
live-examples/css-examples/animation/animation-duration.css
live-examples/css-examples/animation/animation-duration.html
live-examples/css-examples/animation/animation-play-state.css
live-examples/css-examples/animation/animation-play-state.html
live-examples/css-examples/animation/meta.json
live-examples/css-examples/animation/play-pause.js

This PR adds examples for:
* [`animation-direction`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-direction)
* [`animation-duration`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-duration)
* [`animation-play-state`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-play-state)
Let me know if you want to see any changes. Thanks!

Add examples for more animation- properties

---

live-examples/css-examples/flexbox/flex-flow.html

fix no-wrap

---

live-examples/css-examples/animation/animation-timing-function.css
live-examples/css-examples/animation/animation-timing-function.html
live-examples/css-examples/animation/meta.json

This PR adds an example for [`animation-timing-function`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function). Let me know if you want to see any changes. Thanks!

Add example for animation-timing-function CSS property

---

package-lock.json
package.json

You can test this by running:
```
npm run build
npm run tests
```

Updates to the latest jest-puppeteer version

---

CONTRIBUTING.md

Added instructions for contributing HTML examples.

Add HTML instructions

---

css/editor-libs/tabby.css
css/tabbed-editor.css

Further tweaks to HTML editor UI

---

CONTRIBUTING.md

Another attempt at https://github.com/mdn/interactive-examples/pull/702.

Encode '<' and '>' in CONTRIBUTING

---

live-examples/html-examples/css/strong.css
live-examples/html-examples/meta.json
live-examples/html-examples/strong.html

Also a good case for wrapping, I guess.

Add <strong> example

---

live-examples/html-examples/address.html
live-examples/html-examples/css/address.css
live-examples/html-examples/meta.json

As usually, happy for any feedback :)

Add <address> example

---

__tests__/console-utils.test.js
js/editor-libs/console-utils.js

Fix formatArray to support null or undefined as member of array

---

live-examples/css-examples/fonts/font-synthesis.css
live-examples/css-examples/fonts/font-synthesis.html

The Chinese text translates to “When typesetting in Chinese, bold and italic are usually not used.”

More illustrative example for font-synthesis

---

css/editor-libs/tabby.css
css/tabbed-editor.css

More UI updates to the tabbed editor.

fix: update to tabbed editor ui

---

package-lock.json
package.json

Adds additional dev dependencies to ensure prettier, prettier-eslint and prettier-stylelint is always available inside the project.

chore: Adds prettier, prettier-eslint and prettier-stylelint as dev dependencies

---

live-examples/html-examples/inline-text-semantics/css/sub.css
live-examples/html-examples/inline-text-semantics/meta.json
live-examples/html-examples/inline-text-semantics/sub.html

This is almost a direct copy of one of the examples lower down the page, which I thought was hard to improve on.

Add <sub> example

---

live-examples/html-examples/forms/button.html
live-examples/html-examples/forms/css/button.css
live-examples/html-examples/forms/meta.json

as per https://github.com/mdn/interactive-examples/issues/745

adding live example for the button element

---

live-examples/html-examples/inline-text-semantics/css/samp.css
live-examples/html-examples/inline-text-semantics/meta.json
live-examples/html-examples/inline-text-semantics/samp.html

Example for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/samp
Fixes: #786

Add <samp> example

---

live-examples/html-examples/forms/css/textarea.css
live-examples/html-examples/forms/meta.json
live-examples/html-examples/forms/textarea.html

As per https://github.com/mdn/interactive-examples/issues/754

adding textarea element example

---

live-examples/html-examples/demarcating-edits/css/del.css
live-examples/html-examples/demarcating-edits/del.html
live-examples/html-examples/demarcating-edits/meta.json

Add <del> example

---

live-examples/html-examples/content-sectioning/css/hgroup.css
live-examples/html-examples/content-sectioning/hgroup.html
live-examples/html-examples/content-sectioning/meta.json

Add <hgroup> example

---

live-examples/html-examples/text-content/css/dd.css
live-examples/html-examples/text-content/dd.html
live-examples/html-examples/text-content/meta.json

Adds a simple example for the `<dd>` element.

Add <dd> example

---

live-examples/html-examples/text-content/css/p.css
live-examples/html-examples/text-content/meta.json
live-examples/html-examples/text-content/p.html

Example for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p
Nothing really exciting to see here. The idea is that you might want to learn about the differences between `<p>` and `<br>` so I've shown a paragraph with two sentences. Then one with the sentences separated by a `<br>` and then another where the two sentences are both paragraphs. Does this make sense?

Add <p> example

---

live-examples/html-examples/text-content/css/hr.css
live-examples/html-examples/text-content/hr.html
live-examples/html-examples/text-content/meta.json

Example for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr
I wanted to show a bit more styling here as I think `<hr>` can be used nicely for that purpose, so I'm attempting to use some more CSS. Let me know if this is a cool horizontal rule! :slightly_smiling_face:

Add <hr> example

---

live-examples/html-examples/text-content/css/ul.css
live-examples/html-examples/text-content/meta.json
live-examples/html-examples/text-content/ul.html

Example for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul
I thought it would be good to show nesting.

Add <ul> example

---

live-examples/html-examples/inline-text-semantics/css/time.css
live-examples/html-examples/inline-text-semantics/meta.json
live-examples/html-examples/inline-text-semantics/time.html

Example for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time
(fun fact: Chris, Jean-Yves, and I have tickets :tada:)

Add <time> example

---

CONTRIBUTING.md

Changing the TYPE from `html` to `tabbed` did the trick for me.

Change `html` to `tabbed` in Publishing section

---

live-examples/html-examples/inline-text-semantics/css/rt.css
live-examples/html-examples/inline-text-semantics/meta.json
live-examples/html-examples/inline-text-semantics/rt.html

Add rt example.

---

__tests__/puppeteer-tabbed-editor.test.js
css/tabbed-editor.css
js/editor-libs/template-utils.js
package-lock.json
package.json
tmpl/live-tabbed-tmpl.html

Fix https://github.com/mdn/interactive-examples/issues/881 
Tested in Firefox, Firefox Nightly and Chrome

fix(tabbed-editor): Apply output class to output container

---

live-examples/html-examples/inline-text-semantics/css/rtc.css
live-examples/html-examples/inline-text-semantics/meta.json
live-examples/html-examples/inline-text-semantics/rtc.html

Add rtc example.

---

.eslintrc.js
CONTRIBUTING-HTML.md
__tests__/puppeteer-tabbed-editor.test.js
css/tabbed-editor.css
js/editor-libs/template-utils.js
js/editor.js
lib/pageBuilderUtils.js
lib/tabbedPageBuilder.js
live-examples/html-examples/content-sectioning/meta.json
live-examples/html-examples/demarcating-edits/meta.json
live-examples/html-examples/document-metadata/meta.json
live-examples/html-examples/embedded-content/meta.json
live-examples/html-examples/forms/meta.json
live-examples/html-examples/image-and-multimedia/meta.json
live-examples/html-examples/inline-text-semantics/meta.json
live-examples/html-examples/input/meta.json
live-examples/html-examples/interactive-elements/meta.json
live-examples/html-examples/table-content/meta.json
live-examples/html-examples/text-content/meta.json
tmpl/live-tabbed-tmpl.html

@wbamberg Ok so, turns out it was a lot more involved than adding a couple of CSS classes 😄  I separated the work into two commits for easier review. Commit one is the main front end changes, and commit two contains the build and meta changes.

Issue#693 add sizing util classes tabbed editor

---

live-examples/html-examples/inline-text-semantics/css/ruby.css
live-examples/html-examples/inline-text-semantics/meta.json
live-examples/html-examples/inline-text-semantics/ruby.html

Add ruby example.

---

.prettierrc
js/editable-css.js
js/editable-js.js
js/editor-libs/events.js
js/editor.js

@tkadlec Here is the other side of the coin 😄 
*NOTE:* This PR should only be merged after https://github.com/mozilla/kuma/pull/4846 has been merged and pushed to production.

fix(performance): send loadEventEnd to parent via postMessage

---

live-examples/html-examples/inline-text-semantics/meta.json

I've never seen a PR with less urgency than this one :)

Nitpicking: reordering "q" alphabetically in meta.json

---

live-examples/html-examples/inline-text-semantics/sup.html

I think I used eslint too much and my eyes cannot bear an operator without spaces around anymore... :$
Needless to say that this one is not urgent at all :)

<sup>Nitpicking: linting operator with spaces around

---

live-examples/html-examples/forms/option.html
live-examples/html-examples/forms/select.html

https://html.spec.whatwg.org/multipage/form-elements.html#placeholder-label-option

Change <select> examples to use “placeholder label option” pattern

---

live-examples/html-examples/global-attributes/class.html
live-examples/html-examples/global-attributes/css/class.css
live-examples/html-examples/global-attributes/meta.json

Part of this work: https://github.com/mdn/sprints/issues/310

adding class global attribute live example

---

live-examples/html-examples/global-attributes/contenteditable.html
live-examples/html-examples/global-attributes/css/contenteditable.css
live-examples/html-examples/global-attributes/meta.json

Part of this work: https://github.com/mdn/sprints/issues/310

adding contenteditable global attribute example

---

live-examples/html-examples/global-attributes/css/accesskey.css
live-examples/html-examples/global-attributes/css/class.css
live-examples/html-examples/global-attributes/css/contenteditable.css

fix(css), remove font-face imports from global attribute examples

---

live-examples/html-examples/global-attributes/css/dir.css
live-examples/html-examples/global-attributes/dir.html
live-examples/html-examples/global-attributes/meta.json

adding dir global attribute example

---

live-examples/html-examples/global-attributes/css/hidden.css
live-examples/html-examples/global-attributes/hidden.html
live-examples/html-examples/global-attributes/meta.json

adding hidden global attribute interactive example

---

live-examples/html-examples/global-attributes/css/style-attr.css
live-examples/html-examples/global-attributes/meta.json
live-examples/html-examples/global-attributes/style-attr.html

adding style global attribute interactive example

---

live-examples/html-examples/global-attributes/css/id.css
live-examples/html-examples/global-attributes/id.html
live-examples/html-examples/global-attributes/meta.json

adding id global attribute interactive example

---

live-examples/html-examples/global-attributes/css/title-attr.css
live-examples/html-examples/global-attributes/meta.json
live-examples/html-examples/global-attributes/title-attr.html

adding title global attribute interactive example

---

live-examples/html-examples/global-attributes/css/tabindex.css
live-examples/html-examples/global-attributes/meta.json
live-examples/html-examples/global-attributes/tabindex.html

adding tabindex global attribute interactive example

---

live-examples/html-examples/global-attributes/css/spellcheck.css
live-examples/html-examples/global-attributes/meta.json
live-examples/html-examples/global-attributes/spellcheck.html

adding spellcheckglobal attribute interactive example

---

live-examples/js-examples/classes/classes-static.html

Both the class name and example were confusing.

Improve example code

---

live-examples/js-examples/symbol/meta.json
live-examples/js-examples/symbol/symbol-prototype-description.html

Spec: https://tc39.github.io/proposal-Symbol-description/
MDN page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/description (WIP)
Firefox 63, Chrome 70: https://github.com/mdn/browser-compat-data/pull/2693

Add Symbol.description

---

live-examples/js-examples/object/meta.json
live-examples/js-examples/object/object-fromentries.html

DDN bug https://bugzilla.mozilla.org/show_bug.cgi?id=1469019
MDN page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries
Compat data: https://github.com/mdn/browser-compat-data/pull/2692

Add example for Object.fromEntries

---

live-examples/html-examples/input/radio.html

If you omit the `value` attribute in the HTML tag, the submitted form data assigns the value "on" to the group of the radio buttons, it's not very helpful.

Each radio button in the group should have distinct `value` attribute

---

live-examples/html-examples/image-and-multimedia/css/img.css
live-examples/html-examples/image-and-multimedia/img.html

Updated the <img> example to use a CC0 image and
removed the attribution footer

Update <img> to use CC0 image

---

live-examples/html-examples/forms/css/option.css
live-examples/html-examples/forms/option.html

Remove background from option example

---

live-examples/js-examples/promise/promise-resolve.html

Thanks in advance & feedback always welcome 😇

Clarifying Promise.resolve() Example

---

Jenkinsfile

I missed this post-cut-over cleanup as part of the work of last sprint, so doing it now.

remove Jenkinsfile code related to MozMEAO

---

live-examples/css-examples/values-and-units/type-gradient.html

added a 5th example to the interactive example

add conic gradient to gradient page

---

live-examples/js-examples/statement/statement-trycatch.html

Correct spelling from nonExistantFunction to nonExistentFunction

Spelling correction

---

live-examples/css-examples/scrollbars/scrollbar-width.html

Remove length options from scrollbar-width example

---

live-examples/js-examples/intl/intl-listformat.html
live-examples/js-examples/intl/meta.json

Demo to be embed  in [ListFormat Page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ListFormat)

Add Int.ListFormat Demo

---

live-examples/js-examples/array/array-findindex.html

as it doesn't actually find anything but just checks if a number is big

renamed function findFirstLargeNumber to isLargeNumber

---

.travis.yml

Adds https://www.travisbuddy.com/

Add travisbuddy to Travis config

---

live-examples/js-examples/globalprops/globalprops-globalthis.html
live-examples/js-examples/globalprops/meta.json

Adds an interactive example for globalThis.

Add example for globalThis

---

live-examples/js-examples/array/array-join.html

Adding quotes to show output as a string

Small Update Join Docs -- Add quotes to show output as a string

---

live-examples/js-examples/array/array-sort.html

Array sort does not work for numbers.  It is important to highlight this.

highlight gotchas of array sort

---

live-examples/html-examples/inline-text-semantics/cite.html

As per https://github.com/mdn/sprints/issues/1171.
@wbamberg can you give me a quick review? Ta!

correcting semantics for the <cite> example

---

live-examples/js-examples/array/array-splice.html

Index positions stated were incorrect.

Updated comments.

---

live-examples/html-examples/interactive-elements/summary.html

I can't believe I'm trying to correct a riddle – but here we are.
Keyboards sometimes have [locks](https://en.wikipedia.org/wiki/Lock_key). Though as far as I know, they don't have doors.

Update <summary> example content

---

live-examples/html-examples/content-sectioning/address.html

- Fix fake phone number to include proper country code
- Remove unnecessary backslash in `<br>`
- Remove extra `<br>`

Edit <address> example

---

live-examples/html-examples/content-sectioning/footer.html

- Remove space typo
- Add missing comma

Fix typos in <footer> example

---

live-examples/html-examples/content-sectioning/header.html

- Swap `<strong>` for `<em>` ("so" in this context seems to be stressed for emphasis rather than strong urgency)
- Set "beagles" in lowercase
- Add comma
- Use curly apostrophe

Update semantics and grammar for <header> example

---

package.json

Fixed typo on description of package.json

---

live-examples/html-examples/inline-text-semantics/s.html
live-examples/html-examples/text-content/blockquote.html
live-examples/html-examples/text-content/css/blockquote.css

Improve <blockquote> example semantics

---

live-examples/css-examples/lists/counter-set.css
live-examples/css-examples/lists/counter-set.html
live-examples/css-examples/lists/meta.json

This is pretty much the same thing as counter-reset, adding for completeness now Firefox have implemented counter-set.

Adding a counter-set example

---

live-examples/css-examples/text-decoration/text-decoration-color.html

For reference, see the spec for the `currentColor` color keyword:
https://www.w3.org/TR/css-color-3/#currentcolor

Changed `currentcolor` to `currentColor`

---

live-examples/css-examples/lists/counter-reset.html
live-examples/css-examples/lists/counter-set.html

none just none
**counter-reset**
Value:[ \<counter-name\> \<integer\>? ]+ \| none
https://drafts.csswg.org/css-lists-3/#propdef-counter-reset

Fix incorrect syntax for counter-reset and counter-set

---

live-examples/html-examples/table-content/tbody.html
live-examples/html-examples/table-content/tfoot.html
live-examples/html-examples/table-content/thead.html

Just a small grammar fix: https://grammarist.com/usage/stationary-stationery/

Stationary -> Stationery

---

live-examples/js-examples/promise/promise-catch.html

Current practice is to emit errors through console.error().

Updated console.log to console.error

---

live-examples/css-examples/motion-path/meta.json
live-examples/css-examples/motion-path/offset-anchor.css
live-examples/css-examples/motion-path/offset-anchor.html

As per https://bugzilla.mozilla.org/show_bug.cgi?id=1559231 — Firefox now supports offset-anchor, so does Chrome Canary.

adding offset anchor example

---

live-examples/js-examples/number/number-isfinite.html

As pointed out by @PerMildner, `!Number.isFinite` does not imply infinity.
Consider `console.log(div("foo"))`.
Closes #1446

Tweaked Number.isFinite example to be more correct

---

live-examples/css-examples/lists/list-style.css

Removed an unwanted comment ending

Removed unwanted comment ending from css

---

live-examples/js-examples/array/array-copywithin.html
live-examples/js-examples/array/array-entries.html
live-examples/js-examples/array/array-every.html
live-examples/js-examples/array/array-fill.html
live-examples/js-examples/array/array-filter.html
live-examples/js-examples/array/array-find.html
live-examples/js-examples/array/array-findindex.html
live-examples/js-examples/array/array-foreach.html
live-examples/js-examples/array/array-includes.html
live-examples/js-examples/array/array-indexof.html
live-examples/js-examples/array/array-join.html
live-examples/js-examples/array/array-keys.html
live-examples/js-examples/array/array-lastindexof.html
live-examples/js-examples/array/array-length.html
live-examples/js-examples/array/array-map.html
live-examples/js-examples/array/array-pop.html
live-examples/js-examples/array/array-reverse.html
live-examples/js-examples/array/array-shift.html
live-examples/js-examples/array/array-slice.html
live-examples/js-examples/array/array-some.html
live-examples/js-examples/array/array-sort.html
live-examples/js-examples/array/array-splice.html
live-examples/js-examples/array/array-tolocalestring.html
live-examples/js-examples/array/array-tostring.html
live-examples/js-examples/array/array-unshift.html
live-examples/js-examples/array/array-values.html

With this pull request, I try to improve the array related interactive examples by:
- replacing all the `var` declarations with `const`
- replacing function declarations with arrow functions
- adjusting the "expected outputs" to the real outputs (like multiline output and quotation marks)

Use ES6 variable declarations in array examples

---

live-examples/css-examples/fonts/font-variant-caps.html

Fix for https://github.com/mdn/sprints/issues/1996.
@estelle , would you mind reviewing this please, since you filed the issue? Thanks!

Fix property in font-variant-caps example

---

JS-Example-Style-Guide.md

Updated JS-Example-Style-Guide.md with ES6 changes. @wbamberg can you please review.

ES6 updates for the guide

---

live-examples/js-examples/promise/promise-constructor.html
live-examples/js-examples/promise/promise-race.html
live-examples/js-examples/reflect/reflect-deleteproperty.html
live-examples/js-examples/reflect/reflect-ownkeys.html
live-examples/js-examples/reflect/reflect-preventextensions.html

ES6 update for reflect and promise files in js-examples

es6 changes for promise and reflect properties

---

live-examples/js-examples/regexp/meta.json
live-examples/js-examples/regexp/regexp-character-classes.html

As part of https://github.com/mdn/sprints/issues/1721
I was tempted to add an example with emojis as I was unable to do so, please let me know if this is not a good idea, even in interactive-examples :s

Adding regexp character classes

---

live-examples/js-examples/date/date-toprimitive.html
live-examples/js-examples/date/meta.json

Added the date toPrimitive example to the interactive examples page, this is my first contribution on github , so feel free to criticize.

addded Date.prototype[@@toPrimitive] example

---

live-examples/js-examples/regexp/meta.json
live-examples/js-examples/regexp/regexp-groups-ranges.html

Adding another regexp example for https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Ranges as part of https://github.com/mdn/sprints/issues/1721

Adding groups and ranges examples

---

live-examples/js-examples/regexp/meta.json
live-examples/js-examples/regexp/regexp-quantifiers.html

Another set of examples for regexps and https://github.com/mdn/sprints/issues/1721

Adding interactive examples for regexp quantifiers

---

live-examples/js-examples/regexp/meta.json
live-examples/js-examples/regexp/regexp-prototype-dotall.html

Added interative example for dotAll in js-examples, regexp. Also changed the meta.json file.

Added interactive example for dotAll

---

live-examples/html-examples/content-sectioning/section.html

- Promote using h1 once to avoid encouraging bad html practices
- > You should consider avoiding using `<h1>` more than once on a page. See Defining sections for more information.
> [Heading Elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements)

Replace h1 with h2 since its used more than once

---

live-examples/js-examples/classes/classes-extends.js
live-examples/js-examples/classes/meta.json
live-examples/js-examples/date/date-getutcseconds.html
live-examples/js-examples/date/date-getutcseconds.js
live-examples/js-examples/date/date-now.js
live-examples/js-examples/date/meta.json
live-examples/js-examples/expressions/expressions-propertyaccessors.html

With this PR I would like to replace some `.html` source files with `.js` files as the next step in #250.

Replace some .html example sources with .js

---

bin/s3-sync.sh

longer cache for all static assets

---

live-examples/js-examples/intl/intl-displaynames.js
live-examples/js-examples/intl/meta.json

Interactive examples for Intl.DisplayNames (based on issue https://github.com/tc39/ecma402-mdn/issues/1)

Interactive examples for Intl.DisplayNames

---

live-examples/js-examples/expressions/expressions-addition-assignment.js
live-examples/js-examples/expressions/expressions-division-assignment.js
live-examples/js-examples/expressions/expressions-exponentiation-assignment.js
live-examples/js-examples/expressions/expressions-multiplication-assignment.js
live-examples/js-examples/expressions/expressions-remainder-assignment.js
live-examples/js-examples/expressions/expressions-subtraction-assignment.js
live-examples/js-examples/expressions/meta.json

This PR adds arithmetic assignment operator examples https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Assignment_Operators
Will create a second PR of the other assignment operators.

Add arithmetic assignment operators

---

live-examples/js-examples/object/object-entries.js

`let` works fine, but I think in this case, `const` is a better option.

Switch from let to const

---

live-examples/js-examples/expressions/expressions-logical-and-assignment.js
live-examples/js-examples/expressions/expressions-logical-nullish-assignment.js
live-examples/js-examples/expressions/expressions-logical-or-assignment.js
live-examples/js-examples/expressions/meta.json

Examples for 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND_assignment
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment
Quite unsure how AND assignment is useful (at all).

Add logical assignment operators

---

live-examples/js-examples/promise/meta.json
live-examples/js-examples/promise/promise-any.js

For https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any

Add Promise.any

---

live-examples/js-examples/array/array-flat.js
live-examples/js-examples/array/meta.json

Add an example for Array.flat()

---

live-examples/html-examples/image-and-multimedia/css/track.css
live-examples/html-examples/image-and-multimedia/track.html

I've updated the example of the track element because the formatting didn't look well.

Update example for track element

---

live-examples/html-examples/embedded-content/embed.html
live-examples/html-examples/embedded-content/picture.html
live-examples/html-examples/embedded-content/source.html
live-examples/html-examples/forms/css/select.css
live-examples/html-examples/image-and-multimedia/audio.html
live-examples/html-examples/image-and-multimedia/img.html
live-examples/html-examples/image-and-multimedia/track.html
live-examples/html-examples/image-and-multimedia/video.html
live-examples/html-examples/text-content/figcaption.html
live-examples/html-examples/text-content/figure.html

Some media assets no longer load as their location has changed.
fix #1674

(fix) some media assets no longer load

---

live-examples/css-examples/animation/animation-state.js
live-examples/css-examples/animation/play-pause.js
live-examples/css-examples/motion-path/offset-playback.js
live-examples/css-examples/transforms/transform-origin.js

var to const in css-examples js files
Removed unused variables
@wbamberg  Please review

Update Live Examples

---

live-examples/js-examples/intl/intl-datetimeformat-prototype-formattoparts.js
live-examples/js-examples/intl/meta.json

Added Intl.DateTimeFormat.formatToParts() example

---

live-examples/js-examples/string/string-replace.js
live-examples/js-examples/string/string-replaceall.js

String replace and replaceAll improvements

---

live-examples/css-examples/masking/clip-path.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1246764

added path() value example, support in FF63 behind a flag.

---

live-examples/html-examples/content-sectioning/section.html

Fixes https://github.com/mdn/content/issues/1370

updating section example

---

live-examples/html-examples/text-content/li.html

Fix incorrect closing tag for <li> example

---

live-examples/css-examples/logical-properties/border-block-color.html
live-examples/css-examples/logical-properties/border-block-style.html
live-examples/css-examples/logical-properties/border-block-width.html
live-examples/css-examples/logical-properties/border-block.html
live-examples/css-examples/logical-properties/meta.json

Fixes #1637 
Adds `border-block` and longhands.

Adds border-block examples

---

live-examples/js-examples/proxyhandler/proxyhandler-set.js

Hi there! 👋  First of all, let me say that I really appreciate the work that's being put into all of the MDN web documentation, it's a really great resource for beginners and more experienced developers alike!
Just wanted to propose a quick PR to be a bit more instructive in this example - to show that the setter actually does change the value if it doesn't hit this error case with the odd number of monster eyes.

Show that setter does set the property (line 10)

---

live-examples/js-examples/proxyhandler/proxyhandler-set.js

Ref: https://github.com/mdn/interactive-examples/pull/1807#issuecomment-833680392

Switch class to object literal

---

live-examples/js-examples/object/object-prototype-isprototypeof.js

Clarify example. Closes #1622

---

live-examples/js-examples/promise/meta.json
live-examples/js-examples/promise/promise-finally.js

Fixes #1653 
https://user-images.githubusercontent.com/48612525/120126420-0d16df00-c171-11eb-9746-ce7715c4c194.mov

Adds interactive example for Promise.finally()

---

live-examples/css-examples/flexbox/flex-grow.css
live-examples/css-examples/flexbox/flex-grow.html

Add auto width to .example-container for flex-grow interactive demo

---

live-examples/css-examples/flexbox/flex.css
live-examples/css-examples/flexbox/flex.html

Fix responsiveness of .example-container output from `flex` interactive demo

---

live-examples/css-examples/flexbox/flex-shrink.css
live-examples/css-examples/flexbox/flex-shrink.html

Add auto width to .example-container for flex-shrink demo and media query for column layout

---

live-examples/js-examples/array/array-flatmap.js
live-examples/js-examples/array/meta.json

Add interactive example for Array.prototype.flatMap

---

live-examples/css-examples/flexbox/order.css
live-examples/css-examples/flexbox/order.html

Removes inner container for Web/CSS/order interactive demo output

---

live-examples/html-examples/forms/css/textarea.css

Add max-width: 100% to element in demo output for <textarea> HTML page

---

.github/dependabot.yml
.github/workflows/main.yml

github actions

---

live-examples/js-examples/number/number-min-value.js

- #1890 didn't actually fix the issue originally created at mdn/content#7975
- I've changed the example to match the suggestion of the OP

Update example to be unambiguous

---

live-examples/css-examples/basic-box-model/meta.json
live-examples/css-examples/basic-box-model/overscroll-behavior.css
live-examples/css-examples/basic-box-model/overscroll-behavior.html

Partially fixes #1639 
While, the original issue asked for demo example for `overscroll-behavior`. I am intending to fix them incrementally for each property individually.

Adds interactive example for `overscroll-behavior`

---

live-examples/css-examples/basic-user-interface/appearance.html

fix - https://github.com/mdn/content/issues/9043

fix prefix order in appearance (-moz-appearance, -webkit-appearance)

---

.github/workflows/auto-merge.yml
.github/workflows/deploy.yml

Add auto-merge action for dependabot minor version dependency bumps
fix #1935

chore: add auto merge

---

.github/workflows/auto-merge.yml

update permissions for github token

update permissions for github token

---

.github/workflows/auto-merge.yml

do not specify permissions manually

do not specify permissions manually

---

.github/workflows/auto-merge.yml

use gh-token

---

live-examples/js-examples/date/date-tolocaledatestring.js

Fixes https://github.com/mdn/content/issues/10483
As requested in https://github.com/mdn/content/pull/10525

Date.toLocaleDateString() - add note that result depends on timezone

---

live-examples/wat-examples/statements/block.js
live-examples/wat-examples/statements/block.wat
live-examples/wat-examples/statements/br.js
live-examples/wat-examples/statements/br.wat
live-examples/wat-examples/statements/call.js
live-examples/wat-examples/statements/call.wat
live-examples/wat-examples/statements/end.js
live-examples/wat-examples/statements/end.wat
live-examples/wat-examples/statements/if...else.js
live-examples/wat-examples/statements/if...else.wat
live-examples/wat-examples/statements/loop.js
live-examples/wat-examples/statements/loop.wat
live-examples/wat-examples/statements/meta.json
live-examples/wat-examples/statements/nop.js
live-examples/wat-examples/statements/nop.wat
live-examples/wat-examples/statements/return.js
live-examples/wat-examples/statements/return.wat
live-examples/wat-examples/statements/unreachable.js
live-examples/wat-examples/statements/unreachable.wat

Is related to https://github.com/mdn/content/pull/10985 and should be merged at the same time.
(mdn/bob#619 (comment))

Added wasm interactive examples

---

live-examples/css-examples/multi-column-layout/column-fill.html

- fixes #1875 
- Perhaps having `column` property with the `column-fill` in the demo can fill in some details.

Fix column-fill not displaying update

---

live-examples/css-examples/color/color.html

Adding `hwb` syntax to color example

Adding hwb

---

live-examples/css-examples/basic-box-model/clear.css
live-examples/css-examples/basic-box-model/float.css
live-examples/css-examples/basic-box-model/visibility.css
live-examples/css-examples/basic-user-interface/outline-color.css
live-examples/css-examples/basic-user-interface/outline-offset.css
live-examples/css-examples/basic-user-interface/outline-style.css
live-examples/css-examples/basic-user-interface/outline-width.css
live-examples/css-examples/basic-user-interface/outline.css
live-examples/css-examples/basic-user-interface/resize.css
live-examples/css-examples/fonts/font-feature-settings.css
live-examples/css-examples/fonts/font-variant-numeric.css
live-examples/css-examples/fonts/font-variant.css
live-examples/css-examples/lists/counter-reset.css
live-examples/css-examples/lists/list-style.css
live-examples/css-examples/positioned-layout/offsets.css
live-examples/css-examples/positioned-layout/z-index.css
live-examples/css-examples/table/caption-side.css
live-examples/css-examples/text/overflow-wrap.css
live-examples/css-examples/text/tab-size.css
live-examples/css-examples/writing-modes/direction.css
live-examples/css-examples/writing-modes/writing-mode.css

This is the last batch of CSS properties that were not clearly visible on dark mode. I would appreciate it if someone could check whether everything looks ok.
Fixes https://github.com/mdn/content/issues/14301
Fixes https://github.com/mdn/content/issues/14283

CSS dark mode fixes

---

live-examples/js-examples/intl/intl-listformat-prototype-resolvedoptions.js
live-examples/js-examples/intl/meta.json

First time contributing to this project 😄 
#1648
Edit: Oops included the wrong number 🤦‍♂️

 Add example for Intl.listFormat.prototype.resolvedOptions()

---

live-examples/css-examples/basic-user-interface/outline-offset.css

Fix outline-offset in light mode

---

live-examples/css-examples/lists/list-style-position.html

I have made examples be longer, so it is shown how multi line text is aligned.
Examples come from [space.com](https://www.space.com/5853-nasa-memorable-missions.html)

Better list-style-position example

---

live-examples/html-examples/input/checkbox.html

Add fieldset/legend to the checkbox example

---

live-examples/wat-examples/console.js
live-examples/wat-examples/log_bool.js
live-examples/wat-examples/memory/load.js
live-examples/wat-examples/memory/store.js
live-examples/wat-examples/numeric/and.js
live-examples/wat-examples/numeric/clz.js
live-examples/wat-examples/numeric/ctz.js
live-examples/wat-examples/numeric/or.js
live-examples/wat-examples/numeric/popcnt.js
live-examples/wat-examples/numeric/rotl.js
live-examples/wat-examples/numeric/rotr.js
live-examples/wat-examples/numeric/shl.js
live-examples/wat-examples/numeric/shr.js
live-examples/wat-examples/numeric/xor.js
live-examples/wat-examples/statements/block.js
live-examples/wat-examples/statements/call.js
live-examples/wat-examples/statements/nop.js
live-examples/wat-examples/statements/return.js
live-examples/wat-examples/statements/unreachable.js
live-examples/wat-examples/variables/global.js

Needed to display runtime errors mdn/bob/pull/697

Added await to the wasm instantiate calls

---

live-examples/css-examples/logical-properties/margin-block.html
live-examples/css-examples/logical-properties/margin-inline.html
live-examples/css-examples/logical-properties/meta.json

Added margin-block based on margin-block-start and margin-inline based on margin-block-start-start.

margin-block & margin-inline

---

live-examples/css-examples/images/aspect-ratio.css
live-examples/css-examples/images/aspect-ratio.html
live-examples/css-examples/images/meta.json

Interactive example for [aspect-ratio](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio).

aspect-ratio

---

live-examples/css-examples/transforms/function-matrix.html
live-examples/css-examples/transforms/function-matrix3d.html
live-examples/css-examples/transforms/meta.json

I added examples to [matrix](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/matrix) and [matrix3d](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/matrix3d) functions.

Adds matrix & matrix3d functions

---

live-examples/css-examples/pseudo-class/first-child.css
live-examples/css-examples/pseudo-class/first-child.html
live-examples/css-examples/pseudo-class/first-of-type.css
live-examples/css-examples/pseudo-class/first-of-type.html
live-examples/css-examples/pseudo-class/last-child.css
live-examples/css-examples/pseudo-class/last-child.html
live-examples/css-examples/pseudo-class/last-of-type.css
live-examples/css-examples/pseudo-class/last-of-type.html
live-examples/css-examples/pseudo-class/meta.json
live-examples/css-examples/pseudo-class/nth-child.css
live-examples/css-examples/pseudo-class/nth-child.html
live-examples/css-examples/pseudo-class/nth-last-child.css
live-examples/css-examples/pseudo-class/nth-last-child.html
live-examples/css-examples/pseudo-class/nth-last-of-type.css
live-examples/css-examples/pseudo-class/nth-last-of-type.html
live-examples/css-examples/pseudo-class/nth-of-type.css
live-examples/css-examples/pseudo-class/nth-of-type.html

[:first-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:first-child):
[:first-of-type](https://developer.mozilla.org/en-US/docs/Web/CSS/:first-of-type):
[:last-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:last-child):
[:last-of-type](https://developer.mozilla.org/en-US/docs/Web/CSS/:last-of-type):
[:nth-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child):
[:nth-last-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-child):
[:nth-last-of-type](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-of-type):
[:nth-of-type](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-of-type):

Few tree-structural pseudo-classes

---

.github/workflows/publish-release.yml

Adds release-please to help manage releases on the interactive examples repo and also generate release notes for the project.
fix #2109

chore:automation ~ add release please

---

.github/workflows/deploy.yml

only run deploy workflow for release label

fix: only run deploy workflow for release label

---

.github/workflows/deploy.yml

Fixes the syntax for the deploy workflow

fix: deploy workflow

---

.github/workflows/codeql-analysis.yml

Adds `codeql-analysis.yml` to check code security.

feat: create codeql-analysis.yml

---

.github/workflows/publish-release.yml

No need for expression syntax inside `if` conditionals.

fix: remove expression syntax from if conditional

---

.github/workflows/publish-release.yml

Explicitly pass `npm-publish` input as a boolean.

fix: Update publish-release.yml

---

.github/workflows/prod-deploy.yml

Adds a workflow to deploy to production on demand

workflows: add on-demand prod deploy workflow

---

CONTRIBUTING-HTML.md

It adds info about usage of "defaultTab", added in [PR #758](https://github.com/mdn/bob/pull/758)

defaultTab info

---

live-examples/css-examples/images/function-repeating-conic-gradient.html
live-examples/css-examples/images/meta.json

Interactive Example for [repeating-conic-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/repeating-conic-gradient).

repeating-conic-gradient

---

live-examples/css-examples/values-and-units/function-circle.html
live-examples/css-examples/values-and-units/function-ellipse.html
live-examples/css-examples/values-and-units/function-inset.html
live-examples/css-examples/values-and-units/function-path.html
live-examples/css-examples/values-and-units/function-polygon.html
live-examples/css-examples/values-and-units/meta.json

Interactive examples for basic-shape functions: [circle](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/circle), [ellipse](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/ellipse), [inset](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/inset) and [polygon](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/polygon). Theme is the same as in [basic-shape](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape).

Functions circle, ellipse, inset, polygon, path

---

package.json
yarn.lock

Fix `package.json` to allow ranges for dependencies.

chore: fixup package.json
